### ISSUE TITLE
First-time use 

### ISSUE THREAD

**Issue by jerone** [atom-community/sync-settings#100]
Let's create a window where the user can add the gist token, gist id and choose what to backup/restore. While filling in a check could be done if everything is ok. From there the user can backup or restore. If no gist is already created, we should create one and backup immediately.

This will probably lower the barrier for novice users.

**Comment by Spy-Seth** [comment]
Maybe you could propose to automaticly create a new private gist instead of asking the user to do it.

**Comment by voltagex** [comment]
Yeah, it's really hard to find where to enter the first-time settings.

**Comment by dirk-thomas** [comment]
This has been addressed a while ago. A notification message with a link to the package settings is shown: https://github.com/atom-community/sync-settings/blob/dfbe8d7f1d3866593f4fc1816f8bb13fb03211ea/lib/sync-settings.coffee#L127-L138
