### ISSUE TITLE
[Suggestion] Add 'sync' option

### ISSUE THREAD

**Issue by nelson6e65** [atom-community/sync-settings#108]
Should be great ad `Sync` option, in addition to `Backup` and `Restore`, in order to solve possible "merge" conflicts instead of overwrite on multi `backup` calls in multiples instances.

**Comment by mrmckeb** [comment]
Possibly even an auto-sync on startup or shutdown option? But sync is a great idea.

**Comment by jerone** [comment]
[**@mrmckeb**](https://github.com/mrmckeb) commented on [28 jul. 2015 04:38 CEST](https://github.com/Hackafe/atom-sync-settings/issues/108#issuecomment-125415027 "2015-07-28T02:38:52Z - Replied by Github Comment Enhancer"):
> Possibly even an auto-sync on startup or shutdown option? 

Next version will check for possible outdated backups when launching Atom.

**Comment by mrmckeb** [comment]
That sounds great, thanks!

**Comment by johnjcamilleri** [comment]
> Next version will check for possible outdated backups when launching Atom.

Now when I open Atom I seem to always get this message about my settings being out of date. It's not clear what I should do. Is it telling me I should backup (local settings are newer than those in the cloud)? Or that I should restore (settings in cloud are newer than my local ones)? The orange dialog gives me options to do both backup and restore but there's no way of knowing which I should click.

**Comment by groupsky** [comment]
@johnjcamilleri unfortunately right now it's impossible to detect which one is newer. Maybe a good enhancement would be to display backup's date, but local changes are not timestamped so it's up to the user to remember which is more accurate.

**Comment by stechico** [comment]
+1 for sync (auto-sync)

**Comment by yaykyle** [comment]
+1 for auto-sync

**Comment by danielbayley** [comment]
+1 for auto-sync.

**Comment by coolersport** [comment]
If implemented, please make it an opt-in feature. Unless enhancement #281 is in place. This is useful to share settings with the whole team without letting everyone messing it up.

Thanks for this great tool. Tien

**Comment by webberwang** [comment]
+1 for auto-sync

**Comment by UziTech** [comment]
PRs are welcome

**Comment by UziTech** [comment]
Diff view is available now. This will show what changed so you can decide to backup or restore.
