### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by idophio** [atom-community/sync-settings#147]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Mac OS X 10.11.1
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment]
Same happened with Windows (see #148).

**Comment by pencilboy99** [comment]
I have the same error

**Comment by jerone** [comment]
As the error message states _"...authentication requires a token..."_, you need to [add a valid Gist Id and Personal Access Token to the settings](https://github.com/Hackafe/atom-sync-settings#setup).
