### ISSUE TITLE
Latest version instead of backedup version?

### ISSUE THREAD

**Issue by jkw** [atom-community/sync-settings#154]
Is it possible to request this or any way to add it to some config?

**Comment by dirk-thomas** [comment]
Sorry, but I don't understand what this ticket is exactly about. Can you please describe it with a few more words.

**Comment by jkw** [comment]
The backed up versions gets downloaded instead of said packages but latest version during restore of backup. Which often causes errors and needing to force-update right after backup has downloaded old versions of packages. 

Hope that explained a bit better. Typed from my mobile.

**Comment by dirk-thomas** [comment]
Currently `restore` and `update` need to be triggered separately. Imo this makes sense since you might not want to get newer (untested?) versions of packages.

If anyone would like to contribute a PR adding an option for this I am more then happy to review / merge it.
