### ISSUE TITLE
[whilst modifying settings] Uncaught AssertionError: You must pass either an "anonymousId" or a "userId".

### ISSUE THREAD

**Issue by tobypinder** [atom-community/sync-settings#158]
Reproduction Steps 
1. Go to modify sync settings
2. Blank the "analytics user id".

In this case I was using a fresh atom install, and had just unticked the "Analytics" checkbox prior to modifying the analytics user id.

My expectation would be that blanking the field (or malformed identifiers) are handled in some way.

**Atom Version**: 1.3.2
**System**: Linux Mint
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0
### Stack Trace

Uncaught AssertionError: You must pass either an "anonymousId" or a "userId".

```
At assert.js:89

AssertionError: You must pass either an "anonymousId" or a "userId".
    at Analytics.identify (/home/toby/.atom/packages/sync-settings/node_modules/analytics-node/lib/index.js:56:3)
    at /home/toby/.atom/packages/sync-settings/lib/tracker.coffee:42:18
    at /usr/share/atom/resources/app.asar/src/config.js:607:16
    at /usr/share/atom/resources/app.asar/src/config.js:624:20
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:242:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1314:25
```
### Commands

```
  2x -2:06.9.0 core:paste (atom-text-editor#sync-settings.gistId.editor.mini.is-focused)
  2x -0:41.2.0 core:backspace (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "sync-settings": {
    "gistId": "xxxxxxxxxxxxxxxxxxxx",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "analytics": false
  }
}
```
### Installed Packages

``` coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by tobypinder** [comment]
Oops... Thanks. Revoking now.

**Comment by danielbayley** [comment]
Big +1 from me!

This is driving me **nuts**! 😠

It randomly crashes Atom and I loose 20–30 minutes just getting back up and running! I have a lot of packages and probably too many windows open but this is making Atom almost unusable so I’ve had to disable this package, and just because of some analytics! _Even_ though I have `analytics: false` set in my config.

**Comment by dirk-thomas** [comment]
PR #320 should address this issue.
