### ISSUE TITLE
[Discuss] Improve cross platform sync.

### ISSUE THREAD

**Issue by xpol** [atom-community/sync-settings#159]
Current sync-settings not aware of cross platform issues.

Not all items should enabled when sync between platforms.
## Should synced  between platforms:
- Sync installed packages
- Sync user styles
- Sync snippets
## Maybe or may not be:
- Sync Atom's and package settings (they may contains paths)
- Sync user init script
- Sync user defined text files
## Should synced:
- Sync user keymaps

**Comment by rigor789** [comment]
:+1:
I just ran into synced path issues, not that I can't fix the paths manually, but would be cool to have an option to keep some settings local.

**Comment by xpol** [comment]
I currently just sync packages styles and snippets.

**Comment by dirk-thomas** [comment]
The current package settings already allow you to skip certain files from being synced (e.g. the init script). And there is a separate ticket (#165) for ignoring certain entries of the settings (e.g. which contain platform specific paths).

Are there any other cases which this ticket is about?

**Comment by rigor789** [comment]
As far as I can tell (at least for me) #165 covers what I'm missing from the current version! :)

**Comment by schade** [comment]
I experienced this problem in a slightly different way and came up with a solution that may lend itself to sorting this one out. In addition to sync-settings I also use the 'Project Manager' plugin; each machine I work on is multi-OS so pathing differences are always a problem. 'Project Manager' can use the hostname to bypass this issue but can be finicky to setup properly. The filename format for multi-environment usage of this plugin projects.[hostname].cson when 'Environment Specific Projects' is checked in the settings as opposed to the standard of projects.cson. I use 'Sync-Settings' to support backup and restore of these files by placing the correct value for each machine in it's 'Sync-Settings' plugin setting labelled 'Extra Files'. This seems to work for me in preventing path problems between Windows, Linux, and FreeBSD; I hope it gives someone with more free time an idea of how to handle OS differences in a useful manner without resorting to blacklisting values that tend to be a useful application of this package.

**Comment by Duncank** [comment]
This is breaking syncing for me right now; I'm running Atom on Windows and Linux and the Windows version 1.29.0 comes with a newer github package, while Linux is stuck at 1.26.1. 

When I want to restore my settings on Linux, I get a notification "sync-settings: installing github (1/1)", followed by an error: "uncaught error: tried to unload active package 'github'" that tells me "atom is out of date, 1.26.1 is installed, upgrading to the latest version may fix this issue".

**Comment by UziTech** [comment]
The best solution I can think of at the moment is to have separate settings per platform. I don't know of any way for the sync-settings package to know there need to be different versions of packages per platform unless there is a list somewhere.
