### ISSUE TITLE
use any git repo for chinese user who can not use gist 

### ISSUE THREAD

**Issue by ginus** [atom-community/sync-settings#174]
it real a good job for me use atom in four computer, but I con not use gist so store layer can use any git repo is the door for me. others want it?

**Comment by dirk-thomas** [comment]
Since for the maintainers of this package gist works well it is not likely that they will spend time to develop support for a different storage backend. But it would be great if someone would contribute a pull request which implements git repository storage as an alternative to choose from.

**Comment by ginus** [comment]
I have review the code, it not split storage backend from other code, so it is difficult if anyone want contribute a pull request, if maintainers can split it and I can write a git backend.

**Comment by dirk-thomas** [comment]
Many Atom packages are maintained by volunteers. E.g. I have only recently been added as a maintainer for this package and I haven't written any of the existing code myself so it would be the same effort for me as well. Therefore it will require a pull request to add a new future like this.

**Comment by jerone** [comment]
I was once busy with separating all logic into classes, anyone is free to take it further: https://github.com/Hackafe/atom-sync-settings/pull/97

**Comment by jerone** [comment]
I'm closing this issue as won't fix for now. This requires a complete rewrite of the package before other storage's could be considered.
