### ISSUE TITLE
Gist ID not found error

### ISSUE THREAD

**Issue by github-polymer-user** [atom-community/sync-settings#179]
Instruction is not perfect, error accessing gist. Why i can't use a newly created Gist ID?

**Comment by github-polymer-user** [comment]
you have to add a security rights:

gist  Create gists

Please update docs

**Comment by Stibbons** [comment]
indeed this is a small change to the doc that would help a lot!

**Comment by jerone** [comment]
We're open for a PR...

**Comment by jerone** [comment]
Fixed by https://github.com/atom-community/sync-settings/pull/232
