### ISSUE TITLE
Feature request: See diff of local settings and those in gist

### ISSUE THREAD

**Issue by RossBarnie** [atom-community/sync-settings#18]
Before the request I'd like to say I really like this package as is, it's really handy and allowed me to sync my work and home atom settings so thanks for making it :+1: :smile: 

As the title suggests, I'd like to be able to see a diff of my local settings and the remote settings so that I can decide which action (upload vs download) I'd like to perform when I've made a change.

**Comment by jerone** [comment]
:+1:

**Comment by RossBarnie** [comment]
I'm not familiar with coffeescript/javascript or node so I'm not sure how this would be done. I imagine it would have to be something like:

- clone gist to OS's temporary folder
- generate packages.json and settings.json and save to temporary directory
- run OS command to diff the files (See https://github.com/akonwi/git-plus)
- parse diff and display nicely in atom
- remove temporary files (or keep them so we don't have to clone them every time?)

Anyone have any better ideas?

**Comment by groupsky** [comment]
I was thinking of keeping the .atom directory in git, with the user's gist as a remote, then it's simple push/pull to the gist and git will handle the merges and which branch is latest.

**Comment by RossBarnie** [comment]
Yes the merging and such works fine as it is. What I was suggesting was some way of seeing a diff between the local settings and those synced in the gist (similar to if you run the command `git diff HEAD origin/master` in a regular git repo).

**Comment by matmuchrapna** [comment]
Why do you need such diff? If you are programmer and are using only one editor in one moment of time, than you know what you changed some hours earlier on prev machine so you don't want to see the diff, aren't you?

**Comment by RossBarnie** [comment]
Say I've made a change to my local copy (a font change for example), and I've been trying it out for a while without syncing. I make a couple more changes (like updating packages) that I definitely want to keep. If I can see the diff, I can see what my old font was set to and change it back to that, then sync the settings I want to keep.

This particular scenario could also be solved with a patching sync (similar to `git add -p file-to-be-patched `) but this may be overkill.

**Comment by jerone** [comment]
Besides what @RossBarnie mentioned, I think for first-time use it's also very useful.

**Comment by matmuchrapna** [comment]
> If I can see the diff, I can see what my old font was set to and change it back to that, then sync the settings I want to keep.

May be it should be solved with list of changes (revisions) which should be easily revertable.

My point that sync should be seamless and without any questions and popups, like in awesome google chrome.

**Comment by RossBarnie** [comment]
Absolutely, I totally agree that the sync should be seamless. I was suggesting having the diff as another option, separate from the Upload and Download options we have at the moment.

**Comment by matmuchrapna** [comment]
Ok, sorry. My bad. For some reason I thought that you meant popup «Something has changed, here is a diff. Do you want to sync it?»

**Comment by jerone** [comment]
A future vision could be that we provide some sort of UI with two views, one showing the current situation and one showing the backed up situation. The user could then select which options (config, packages, snippets, ...) to back up. And also select which options to restore. A visual diff would show the differences. Nice arrow buttons would show the direction of the options (backup vs restore).

**Comment by Cphoenix** [comment]
+1 bajillion bajillions. I'd love such a feature, mostly because I accidentally nuked a bunch of my snippets recently and had to go digging through the Gist web interface to find the ones that got killed. It was not a pleasant experience, that's for sure.

**Comment by UziTech** [comment]
I implemented this feature in #490 I would like some feedback on how it can be more useful before it gets merged.
