### ISSUE TITLE
Move repo to atom-community

### ISSUE THREAD

**Issue by dirk-thomas** [atom-community/sync-settings#227]
We would like to move this repo to the atom-community as https://github.com/atom-community/sync-settings

@groupsky @jerone Since you suggested this initially I assume you are ok with this but please comment here to confirm.

@joefitzgerald Can you please add admin access to the two current owners above. They can then readd me so that I can continue to make contributions as well as releases. Thanks,

**Comment by jerone** [comment]
This seems perfect to me as @groupsky agrees too :+1:

**Comment by joefitzgerald** [comment]
Keep in mind you'll want to update:

* https://github.com/Hackafe/atom-sync-settings/blob/9e81322c8069ab623009e26632857b9778c04396/package.json#L8
* https://github.com/Hackafe/atom-sync-settings/blob/9e81322c8069ab623009e26632857b9778c04396/package.json#L12
* https://github.com/Hackafe/atom-sync-settings/blob/9e81322c8069ab623009e26632857b9778c04396/package.json#L15
* Your settings for your `origin` remote in your local working copies

...after the move, and then publish a patch release of the package.

**Comment by jerone** [comment]
Steps to do when all agree:

1. [ ] Transfer ownership within the settings page.
2. [ ] Rename repo from `atom-sync-settings` to `sync-settings`.
3. [ ] Update links as [mentioned](https://github.com/Hackafe/atom-sync-settings/issues/227#issuecomment-194461618) by @joefitzgerald and in the readme.
4. [ ] Publish new version.
5. [ ] Figure out Gitter link.

**Comment by dirk-thomas** [comment]
+1

**Comment by groupsky** [comment]
:+1: for the transfer. @jerone, @dirk-thomas let me know when it's ok to make the transfer

I think it's a good idea to announce the transfer before it happens, in case any contributor is working on something.

**Comment by dirk-thomas** [comment]
As far as I know GitHub will automatically provide redirects. I haven't seen any major contributions recently (which where not from me :wink:). So anytime is fine by me.

**Comment by groupsky** [comment]
ok then, I'll transfer the ownership in 10 mins

**Comment by groupsky** [comment]
[bump](https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations), @joefitzgerald has to make me admin of atom-community to perform the transfer, so we're waiting on this event.

**Comment by jerone** [comment]
Yesterday I made @dirk-thomas admin of this repo, so he can do the transfer or I can when I'm at work or we wait for you to be added as admin...

**Comment by groupsky** [comment]
@joefitzgerald I've added you as admin to this repo, so you may initiate the transfer. From the [docs](https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations) I understand that only user that is both admin of the receiving organization and admin of the repo can make the transfer.

**Comment by jerone** [comment]
>  You don’t have admin rights to atom-community 

Being part of a team from atom-community is apparently not enough to transfer the repo.

@joefitzgerald Hope you have time to transfer this repo.

**Comment by joefitzgerald** [comment]
The repo has been moved.

**Comment by jerone** [comment]
@atom-community/atom-sync-settings-maintainers Please update your repository origin path to the new location. This is required for publishing.

**Comment by jerone** [comment]
@joefitzgerald I've renamed the package to remove the `atom-` prefix. Probably want to do that with the team `atom-sync-settings-maintainers` too.

**Comment by joefitzgerald** [comment]
> Probably want to do that with the team atom-sync-settings-maintainers too.

Done :+1:.
