### ISSUE TITLE
Feature Request: Using a Git repository that is not hosted on GitHub.com

### ISSUE THREAD

**Issue by cybik** [atom-community/sync-settings#253]
I know Atom.io is basically backed by GitHub, but what about the nerds that would want to use Atom and sync their settings to, for example, a repo hosted on a corporate GitHub instance? 

Or a Bitlocker instance? Or Gerrit, or Gitlab, or backing up the config onto a bare repo locally that's then served through an NFS filesystem mount onto a local network (unsecure, I know, but still), or using SMB, or whatever?

**Comment by dirk-thomas** [comment]
Please see #236 and #174 which requested a similar feature.

**Comment by cybik** [comment]
Wontfix based on previous issues.
