### ISSUE TITLE
Failure then Success after upgrade to 0.7.2

### ISSUE THREAD

**Issue by justinaray** [atom-community/sync-settings#256]
After upgrading to the latest sync-settings (0.7.2), the Backup command is failing first and then succeeding.

The UI gets a Red 'Server Error' box but then a green confirmation box  beneath it.  Confirmed on github directly that the updates are being made and the gist is being rev'd.

It looks like the call is failing with a 500.
```
error backing up data: {
    "message": "Server Error",
    "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"
}
```

After that, the console prints the following twice:  `Creating GitHubApi client with token = FOOBARBAZ`

Atom Version: 1.7.0-beta0

**Comment by dirk-thomas** [comment]
The server error looked like a one-time hickup of the Github API.

I will close this ticket for now. Please feel free to comment if it happens again and this can reopened.
