### ISSUE TITLE
How do we prevent sensitive information from being synced?

### ISSUE THREAD

**Issue by mautematico** [atom-community/sync-settings#257]
When ussing https://github.com/imdone/imdone-atom-github, as well as some other atom packages, sensitive information (like github tokens) is available on a (most of the time) public gist, like this github token of me:

https://gist.github.com/mautematico/51409ae96652705e33a6/9e7ca6b4eddb09c199036c1942f968fdc3021269#file-settings-json-L41

Is there a _standard_ way of preventing this?

I've already open an issue on imdone-atom-github for its particular case:
https://github.com/imdone/imdone-atom-github/issues/11

May be they will need some help to implement this hipotetical _standard_ way. :)

Please give it a look to sync-settings issues and PRs:
https://github.com/atom-community/sync-settings/issues/14
https://github.com/atom-community/sync-settings/issues/49

Thank you for the hard work!

**Comment by dirk-thomas** [comment]
This package has a configuration option for that: see https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/lib/config.coffee#L22

**Comment by mautematico** [comment]
Awesome!

I'll try to use the blacklist and I'll report the results back and create a
mini how-to for `imdone-atom-github`

Thank you very much!

---
Doing good is part of our code.
mozilla.org

Sent from my Firefox OS

**Comment by vjpr** [comment]
This issue can probably be closed.

**Comment by dirk-thomas** [comment]
Thanks for the reminder.

**Comment by mautematico** [comment]
Yes, sorry.

What @dirk-thomas suggested worked just fine. :)
