### ISSUE TITLE
Integration with Atom Tool Bar

### ISSUE THREAD

**Issue by Mayccoll** [atom-community/sync-settings#261]
It would be nice an integration with [Atom Tool Bar](https://atom.io/packages/tool-bar) and [Flex Tool Bar](https://github.com/cakecatz/flex-toolbar).
Tnks

**Comment by jerone** [comment]
I have the following code in my `toolbar.cson`:

```cson
  {
    type: "button"
    icon: "cloud-upload"
    callback: "sync-settings:backup"
    tooltip: "Backup (Sync Settings)"
    iconset: "fa"
  }
  {
    type: "button"
    icon: "cloud"
    callback: "sync-settings:view-backup"
    tooltip: "View backup (Sync Settings)"
    iconset: "fa"
  }
  {
    type: "button"
    icon: "cloud-download"
    callback: "sync-settings:restore"
    tooltip: "Restore (Sync Settings)"
    iconset: "fa"
  }
```

**Comment by Mayccoll** [comment]
Hi, Thanks. But what I meant was to synchronize the file ```toolbar.cson``` :smile:

**Comment by jerone** [comment]
There's an extra setting called "Extra Files". Just add your `toolbar.cson` file and backup.

**Comment by dirk-thomas** [comment]
As mentioned before this can already be done.
