### ISSUE TITLE
Explicit settings to sync specific files from other packages e.g. projects.cson

### ISSUE THREAD

**Issue by andrewbanchich** [atom-community/sync-settings#264]
Would it be doable to add the ability to sync projects as well as settings?

**Comment by obust** [comment]
It is actually possible to sync `projects.cson` by adding it to the "Extra Files" list in the settings of sync-settings package.

However I agree that it should be a standard file available for syncing with a checkbox along with packages, keymaps, styles, etc...

**Comment by dirk-thomas** [comment]
Imo the existing option to add the file to the "Extra files" is sufficient. But if anyone would like contribute a PR which adds an explicit option for this file I would be happy to review / merge.

**Comment by Strae** [comment]
I've tryed to use the Extra Files field (`~/.atom/projects.cson`), but I got this error when I try to make a backup:
`sync-settings: Error backing up your settings. (Validation Failed)`

**Comment by dirk-thomas** [comment]
Can you please check the debug console for more output. This line (https://github.com/atom-community/sync-settings/blob/538b24c89096bb168a189838338f670a55bd64f2/lib/sync-settings.coffee#L171) should output some more information which might be helpful.

**Comment by Strae** [comment]
@dirk-thomas ahhh got it, my bad, I didnt see that the file must be inside ~/.atom (I was using the full path of the file)

It works now ;)
