### ISSUE TITLE
sync-settings: Error backing up your settings. (Gist ID Not Found)

### ISSUE THREAD

**Issue by freqn** [atom-community/sync-settings#265]
I set my gist id and keep getting this error when attempting a backup.

`sync-settings: Error backing up your settings. (Gist ID Not Found)`

Gist ID is [c9a9babfa1d04a76dda7b9ce1c14c842](https://gist.github.com/freqn/c9a9babfa1d04a76dda7b9ce1c14c842)

**Comment by cliffordfajardo** [comment]
@freqn how did you get it to sync? After your comment ^^ 2 days later your atom-sync settings gist was updated.

**Comment by buzzswarbrick** [comment]
@cliffordfajardo I was getting this error, to fix I had to make sure in my 'Edit personal access token' that 'Gist' was selected and updated. (my bad for not reading the instructions completely)

**Comment by leoatchina** [comment]
sync-settings: Error backing up your settings. (Gist ID Not Found)

same problem

**Comment by maxwellzdeamon** [comment]
Leoatchina,

1.  go to your github settings (profile dropdown menu located upper right corner)

**Comment by dirk-thomas** [comment]
I will close this ticket since it should be covered by the [setup instructions](https://github.com/atom-community/sync-settings#setup). If anyone would like to improve the instructions PRs are always welcome :wink:

**Comment by josemera** [comment]
so where do I find the gist ID ?  I have done all the steps described here and I am given a gitst *token* but not a gist ID

**Comment by dafuyi** [comment]
OMG, I forget my old token, and create new one. Then, the problem appeared. 

I GOT IT.

**Comment by webmasterpf** [comment]
Thanks for the tips.
