### ISSUE TITLE
Option to sync as repo instead of gist?

### ISSUE THREAD

**Issue by danielbayley** [atom-community/sync-settings#267]
Since Gists don't support directories, it would be handy if we could have the ability to sync to a GitHub repository.

For example, my package [modular-keymaps](https://atom.io/packages/modular-keymaps) allows `keymap.cson` to be split into multiple files (in an `ATOM_HOME/keymaps` subdirectory). There are other packages that do similar things, and I have a number of others in the works. But obviously these won't work with _sync-settings_ as it currently only supports syncing with a Gist.

**Comment by dirk-thomas** [comment]
It should be possible to sync all the files in that subfolder to a gist if the config would / does support a wildcard matching. No need for a different storage backend for that.

**Comment by danielbayley** [comment]
So you think multiple Gists would be a better solution as opposed to a repository/.gitignore approach?

Could a restore recreate the folder structure?

**Comment by dirk-thomas** [comment]
This plugin already syncs multiple files into a single gist. No need for multiple gists.

**Comment by danielbayley** [comment]
Providing the folder structure is restored along with everything else, and #258 is implemented I suppose that would cover this functionality well enough.

**Comment by kachkaev** [comment]
I agree with @danielbayley that syncing via a git repo would be helpful. And it does not have to be github. I can imagine having single a private git repo that we share with our colleagues and pull from when someone has discovered a new nice Atom package.

`Sync settings: backup` will change the files in a repo but it does not have to commit or push. The benefit from using the plugin will be in that it will install and delete Atom packages (this won't happen if I just turn `~/.atom/*.cson` into a repo myself.

**Comment by edobry** [comment]
This would be extremely useful! Allowing non-gist backends would make this package infinitely more versatile. 👍  from me

**Comment by UziTech** [comment]
PRs are welcome

**Comment by UziTech** [comment]
Sync-Settings now allows other packages to provide a location for the backup. You can install [sync-settings-git-location](https://atom.io/packages/sync-settings-git-location) and follow the install instructions to use a git repo for the backup location.
