### ISSUE TITLE
automatic sync triggered on settings change

### ISSUE THREAD

**Issue by iamstarkov** [atom-community/sync-settings#27]
It is on roadmap, so what is the status of this feature?

**Comment by iamstarkov** [comment]
ping

**Comment by rcrooks** [comment]
+1 -- this would be a great option for this awesome package

**Comment by dbkaplun** [comment]
Just wanted to post this comment from #143, in case it gets lost in the fray:
> It doesn't even have to watch for changes, it can simply compare the old backup against a new backup every 24 hours.

**Comment by fuzzy76** [comment]
This is really needed. There is no point for me even installing sync-settings like this. I know I will never remember to backup my settings every time I change anything.

**Comment by dirk-thomas** [comment]
If this feature is important to you please consider creating a pull request.

**Comment by UziTech** [comment]
I'm closing this in favor of #317
