### ISSUE TITLE
Make it possible to config CAs for the package

### ISSUE THREAD

**Issue by michael-yx-wu** [atom-community/sync-settings#270]
I'd like to use this behind a corporate firewall that swaps unpinned root CA certs for our own root CA to inspect network traffic. If I could specify the CA(s) to trust, then I could continue using sync-settings while at work.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this feature.

**Comment by UziTech** [comment]
With the new [Location Service](https://github.com/atom-community/sync-settings#location-service) you could create a package that does this. If you need any help creating the location service package let me know.
