### ISSUE TITLE
Running a backup is modifying my config.cson file.

### ISSUE THREAD

**Issue by spAnser** [atom-community/sync-settings#274]
It is changing all instances of `"\n"` into

```
'''


'''
```

Turning one new line into multiple lines indented.

My gist appears to have the `"\n"` in it so it happens on re-import.

**Comment by darith27** [comment]
I'm having this problem also when running backup it converts my "\n" into the spaces @spAnser displayed above.

**Comment by dirk-thomas** [comment]
On backup this package only writes the version of the backup to the config file: https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/lib/sync-settings.coffee#L182

If this is altering your configuration in any other way this might be an upstream problem. Therefore I don't think this package can do anything about it. Maybe consider creating a ticket upstream?

**Comment by spAnser** [comment]
My problem is this.... http://puu.sh/pPhMa/53e94aae62.png

The backup is correct but upon restoring it changes \n to multple new lines and spaces

**Comment by spAnser** [comment]
Decided to finally dig through the code some to see what is going on.

Essentially sync-settings is running this command. `atom.config.set('csscomb.space-after-opening-brace', "\n")` Which sets the value in atom and then atom resaves config.cson. Upon atom resaving it turns into:
```
    "space-after-opening-brace": '''
                                    
                                    
    '''
```

If I try running `atom.config.set('csscomb.space-after-opening-brace', "\\n")`. Upon atom resaving `config.cson` it turns into:
```
    "space-after-opening-brace": "\\n"
```

This is also the expected outcome and doesn't work as a value with csscomb.

**Comment by dirk-thomas** [comment]
To clarify: the configuration file is *not* being modified when you run the "backup" command. It is being modified when you "restore" a previous backup?

That looks like a problem with escaping when restoring configuration values then.

**Comment by spAnser** [comment]
Yes it happens on restore. My latest comment narrowed it down to an atom issue I think.

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
