### ISSUE TITLE
Error backing up your settings (Validation Failed)

### ISSUE THREAD

**Issue by batjko** [atom-community/sync-settings#275]
Hi there,

I've just installed this package and followed the instructions to the letter. And yet:
![image](https://cloud.githubusercontent.com/assets/7287076/16335188/2c150888-39fd-11e6-8f94-bfffd3042ff2.png)

My gist is currently empty, except for a single comment, and when starting Atom, the package does seem to recognize that my gist is "out of date", offering to back up.
However, When trying to do just that either via the command pallette or by clicking the button offered by the OutOfDate message), I get this error above.

What validation exactly fails here? What's missing?

**Comment by dirk-thomas** [comment]
The error message is generated [here](https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/lib/sync-settings.coffee#L180). So the `Validation Failed` part is coming from the GitHub server when trying to edit the gist. The error message is described in GitHub's API: https://developer.github.com/v3/#client-errors

I am not sure what the reason could be. Can you please run `atom` with `-d` and then open the developer console (Right click -> Inspect Element, Console tab) before triggering a backup. Than you should be able to see an error message starting with "error backing up data:". Can you please post the full content of that message. Maybe the content of the "Validation Failed" response will shed some light into this.

**Comment by batjko** [comment]
Ok, so... I did the above and this is the error the console gives me:

![image](https://cloud.githubusercontent.com/assets/7287076/16358888/0d0e9db4-3b1a-11e6-8ee8-b24c102b0d36.png)

Not sure if this tells us any more than what you've already explained above, @dirk-thomas ?

**Comment by neurovertex** [comment]
Just ran into this issue. Figured out that I had a file in the "Extra Files" that was not in .atom/ directly, thus the / in the path (I assume) were causing the issue

**Comment by batjko** [comment]
I don't use the "Extra Files" feature (unless there is some default I am not aware of?).
I only installed the package, added a new token and the gist ID as instructed, and there's the error.

Still no idea what to do about it.

**Comment by dirk-thomas** [comment]
@batjko Can you please post the version number of `sync-settings` you are using? Also the configuration of `sync-settings` from the `config.cson` file (redacting your private info) might be helpful.

**Comment by batjko** [comment]
@dirk-thomas I have not tried this package since that comment 6 months ago. 
I will try it again and post the result with the requested details.

**Comment by dirk-thomas** [comment]
I will close this due to no response. Please feel free to comment here with the requested information and the ticket can be reopened.

**Comment by oXis** [comment]
I don't know, but I might have found the bug. I occurs when a file to backup is empty but exists, for example I my case, it was keymap.cson.
I was playing around with the code near the error message and when commenting this line
`if atom.config.get('sync-settings.syncKeymap')
      files["keymap.cson"] = content: (@fileContent atom.keymaps.getUserKeymapPath()) ? "# keymap file (not found)"`
the backup up worked. So I went to the settings of `sync-settings` and untick backup keymap, and I worked.

**Comment by BuddhikaGeasman** [comment]
> I don't know, but I might have found the bug. It occurs when a file to backup is empty but exists, for example in my case, it was keymap.cson.
> I was playing around with the code near the error message and when commenting this line
> 
> > if atom.config.get('sync-settings.syncKeymap')
> > files["keymap.cson"] = content: (@filecontent atom.keymaps.getUserKeymapPath()) ? "# keymap file (not found)"
> 
> the backup up worked. So I went to the settings of `sync-settings` and untick backup keymap, and it worked perfectly.

Yes unchecking `keymap` helps to backup without validation fail error
