### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME\*'

### ISSUE THREAD

**Issue by dustycodes** [atom-community/sync-settings#278]
[Enter steps to reproduce below:]
1. Have outdated settings
2. Click the restore option

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\dusty.atom*'

```
At fs.js:584

Error: ENOENT: no such file or directory, open 'C:\Users\dusty\.atom\*'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at file:///C:/Users/dusty/.atom/packages/sync-settings/lib/sync-settings.coffee:233:19
    at C:\Users\dusty\.atom\packages\sync-settings\node_modules\github4\index.js:759:17
    at callCallback (C:\Users\dusty\.atom\packages\sync-settings\node_modules\github4\index.js:613:17)
    at IncomingMessage.<anonymous> (C:\Users\dusty\.atom\packages\sync-settings\node_modules\github4\index.js:671:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
     -8:45.8.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:14.2.0 sync-settings:check-backup (div.package-detail.panels-item)
     -3:09.2.0 sync-settings:view-backup (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:04.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "1f877bf5-621e-418c-9d88-905689dfa39f",
    "_lastBackupHash": "d240d27a94ea21ccaba21a18c97cc8931d4317f3",
    "gistDescription": "automatic update by http://atom.io/packages/sync-settings ",
    "gistId": "MYID",
    "personalAccessToken": "MYTOKEN"
  }
}
```
### Installed Packages

``` coffee
# User
php-cs-fixer, v2.5.6
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
The error seems to be related to the `extraFiles` you have configured. Can you please post what `extraFiles` are listed in the gist you are trying to restore?

**Comment by dustycodes** [comment]
Is the extraFiles a setting? I don't have the setting configured in any of the Gist. I do have several files if thats the extraFiles you are looking for. They all are the default I believe though: init.coffee, keymap.cson, packages.json, settings.json, snippets.cson, styles.less

**Comment by dirk-thomas** [comment]
`Extra Files` is a setting for this package. You can list files which should be backed up beside the "standard" files. For the standard files the settings offer multiple checkboxes (e.g. for the settings, package list, keymap, styles, init, snippets, etc.). Therefore it would help if you can check the value of the extra files in your settings and post its content. Maybe it contains a wrong value or just spaces?

**Comment by dustycodes** [comment]
Oh ok. I checked and it was empty.

**Comment by dirk-thomas** [comment]
The stacktrace indicates that [sync-settings.coffee:233](https://github.com/atom-community/sync-settings/blob/65ae3fe9487db898403b33af95e0b0e4156cebf2/lib/sync-settings.coffee#L233) is trying to restore a non-standard file from your Gist. Can you please post a complete list of filenames stored in your Gist.

**Comment by dustycodes** [comment]
Awesome. I just got it. I had a file in the Gist with * in it. I don't know if that should be allowed or not. But that was the issue.

**Comment by dustycodes** [comment]
Do you want me to close this?

**Comment by dirk-thomas** [comment]
Thank you for keep digging into it and I am glad you found the source of the problem.

The error message actually already points out that `*` (see `C:\Users\dusty\.atom\*`). Since I don't see what we could change in this package to handle this differently I guess the ticket can be closed.
