### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by Alan-tao** [atom-community/sync-settings#280]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment]
Please provide the steps to reproduce.

**Comment by dirk-thomas** [comment]
I am closing for now due to no response. Please feel free to post more information and this ticket can be reopened.
