### ISSUE TITLE
Read operations require an auth token

### ISSUE THREAD

**Issue by moorage** [atom-community/sync-settings#281]
Shouldn't you be able to fetch settings without a token, just from a secret gist?
1. Don't fill in auth token
2. Fill in gist id

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2
### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment]
The package always uses the GitHub API with authentication. While read operations could be done without this is currently not supported. It would be great to add this feature. Could you provide a pull request for this use case?

**Comment by UziTech** [comment]
PRs are welcome

**Comment by 222YEDONG** [comment]
使用GitHub还有atom 和这个插件不久。最近频繁收到GitHub发来的邮件，好像和这个插件有关，突然发现插件更新了，不知道会不会好点，之前一直有红色的警告提示。以下是内容：
![image](https://user-images.githubusercontent.com/44609485/75682959-38dab900-5cd1-11ea-8543-44cdf139e408.png)
---
for authentication via URL query
parameters
GitHub
Hi@222YEDONG,
On February 19th,2020 at 11:59(UTC)your
personal access token(Atom)using
NodeJS HTTP Client was used as part of a
query parameter to access an endpoint
through the GitHub APl:
https://api.github.com/gists/7e05068310ae
21c743e048f67461fc1c
Please use the Authorization HTTP header
instead,as using the `access_token`query
parameter is deprecated.If this token is
being used by an app you don't have control
over,be aware that it may stop working as a
result of this deprecation.
Depending on your APl usage,we'll be
sending you this email reminder on a
monthly basis for each token and User-
Agent used in API calls made on your
behalf.
Just one URL that was accessed with a
token and User-Agent combination will be
listed in the email reminder,not all.
Visit
https://developer.github.com/changes/202
0-02-10-deprecating-auth-through-query:
param for more information about
suggested workarounds and removal dates.
Thanks,
The GitHub Team
图片由回QQ邮箱生成
反馈

**Comment by UziTech** [comment]
@222YEDONG that is fixed in the lastest version #463
