### ISSUE TITLE
sync-settings: Error backing up your settings. (Server Error)

### ISSUE THREAD

**Issue by fly1ted** [atom-community/sync-settings#287]
I get an err and success at the same time.

![image](https://cloud.githubusercontent.com/assets/8587695/17049312/3cd60c04-4ff5-11e6-9536-c7d95a25809e.png)

**Comment by lharper** [comment]
I get the same issue.

**Comment by dirk-thomas** [comment]
Please check the output on the developer console and post the full error message starting with `error backing up data:`.

**Comment by puregardenia** [comment]
I got the same problem.

```
Creating GitHubApi client with token = ...

tracker.coffee:54 tracking Backup

sync-settings.coffee:243 Creating GitHubApi client with token = ...

tracker.coffee:54 tracking Backup
```

`
error backing up data: {"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"} e…s.HttpError {message: "{"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}", code: 500}code: 500message: "{"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}"__proto__: Errorconstructor: (message, code)toJSON: ()toString: ()__proto__: Object(anonymous function) @ sync-settings.coffee:177global.sendError @ C:\Users\admin\.atom\packages\sync-settings\node_modules\github4\index.js:729(anonymous function) @ C:\Users\admin\.atom\packages\sync-settings\node_modules\github4\index.js:736callCallback @ C:\Users\admin\.atom\packages\sync-settings\node_modules\github4\index.js:613(anonymous function) @ C:\Users\admin\.atom\packages\sync-settings\node_modules\github4\index.js:668emitNone @ events.js:91emit @ events.js:185endReadableNT @ _stream_readable.js:974_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
`

**Comment by Egidius** [comment]
Same here, plugin seems to write to the gist though

**Comment by dirk-thomas** [comment]
I can't reproduce the problem. So I can't suggest anything to address the problem. It looks weird that both notification show up - especially since only one of them can happen in a single `backup` call (see https://github.com/atom-community/sync-settings/blob/master/lib/sync-settings.coffee#L180-L187).

**Comment by psykzz** [comment]
For me it looks like the commands are running 4 times.

This is the output from `check backup`

```
sync-settings.coffee:70 checking latest backup...
sync-settings.coffee:258 Creating GitHubApi client with token = <token>
sync-settings.coffee:70 checking latest backup...
sync-settings.coffee:258 Creating GitHubApi client with token =  <token>
sync-settings.coffee:70 checking latest backup...
sync-settings.coffee:258 Creating GitHubApi client with token =  <token>
sync-settings.coffee:70 checking latest backup...
sync-settings.coffee:258 Creating GitHubApi client with token =  <token>
(4) sync-settings.coffee:89 latest backup version a9e655ed84203a10a48e6228de02b155f0c9e498
```

**Comment by dirk-thomas** [comment]
@psykzz I can't reproduce that output. When invoking the `check output` command I see the following three lines exactly once:

```
checking latest backup...
Creating GitHubApi client with token = xxxxx
latest backup version yyyyy
```

Please provide more information if the problem persists for you.

**Comment by martiqc** [comment]
Guys, I had the same problem : backup successful with server error.
I haven't checked the output though. All I can say is that I did not restart Atom after installing sync-settings.
I tried to restart Atom, no more error! Backup is still working fine since then.

Can this info help you @dirk-thomas ?
I am running Atom on Linux Mint 18 Cinnamon 64-bit

**Comment by jaconey** [comment]
I seconded @martiqc. I hit the Server 500 error even when backup succeeded.  But restarting Atom fixed it.  I'm on macOS Sierra.

**Comment by srMarquinho** [comment]
Well, not quite the same as I'm not getting a successful backup. Please let me know if should move this somewhere else.
My last successful backup was 23 days ago.

```
error backing up data: {"message":"Server error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"} 

exports.HttpError
code: 500
headers: Object
access-control-allow-origin: "*"access-control-expose-headers: "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"connection: "close"content-length: "99"content-security-policy: "default-src 'none'"content-type: "application/json; charset=utf-8"date: "Wed, 06 Dec 2017 11:15:13 GMT"server: "GitHub.com"status: "500 Internal Server Error"strict-transport-security: "max-age=31536000; includeSubdomains; preload"x-accepted-oauth-scopes: ""x-content-type-options: "nosniff"x-frame-options: "deny"x-github-media-type: "github.v3; format=json"x-github-request-id: "C5B4:0184:C39682:1E505CE:5A27D141"x-oauth-scopes: "gist"x-ratelimit-limit: "5000"x-ratelimit-remaining: "4993"x-ratelimit-reset: "1512561310"x-runtime-rack: "0.195938"x-xss-protection: "1; mode=block"
__proto__: Object
message: "{"message":"Server error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}"status: "Internal Server Error"
__proto__: Error
(anonymous) @ C:\Users\Marco Araujo\.atom\packages\sync-settings\lib\sync-settings.coffee:247
```
It is a windows machine.

Thanks! :)

**Comment by monster010** [comment]
@dirk-thomas The problem does only exists if Sync Keymap, Sync Styles, Sync Init and or Sync Snippets is activ. I think the problem is that these files do not exist on everyone.

**Comment by nerakhon** [comment]
@dirk-thomas The originally reported issue presents itself only when sync-settings is installed for the first time, configured and used without a restart of Atom. After the first restart it's gone, I hope that will help with reproducing the issue.

**Comment by dirk-thomas** [comment]
I currently don't have any time to spend on this package. Please consider investigating the problem and proposing a pull request.

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
