### ISSUE TITLE
sync-settings: Error backing up your settings. (Bad credentials)

### ISSUE THREAD

**Issue by chensource** [atom-community/sync-settings#288]
![image](https://cloud.githubusercontent.com/assets/7836268/17085075/b9c46518-5201-11e6-9df2-726f7d0fa670.png)

**Comment by dirk-thomas** [comment]
If the API call to GitHub responded with "Bad credentials" you should double check you API token. GitHub is not accepting it as valid.

**Comment by midgethoen** [comment]
I was having the same issue.
Turns out sync-settings prefers the GITHUB_TOKEN env variable and I had an invalid token set there...
