### ISSUE TITLE
Support syncing of language specific settings

### ISSUE THREAD

**Issue by r-chris** [atom-community/sync-settings#289]
Is there a reason the `config.cson` file is not included in the backup/sync?
There must be a reason for it, ideally another than "it may contain sensitive information".

It seems like a reasonably important file when syncing settings is concerned. For example people would have to use this file to add configuration related to the whitespace package here, which doesn't show up anywhere else.

**Comment by dirk-thomas** [comment]
What makes you think that the settings from that file are not being backed up? `atom.config.settings` is being backed up which contains the settings from the `config.cson` file minus blacklisted keys.

**Comment by r-chris** [comment]
That file or the relevant settings I was interested in syncing certainly are not showing up in the gist. Is there somewhere else that I might miss, where they would be synced to?

**Comment by dirk-thomas** [comment]
The Gist should contain a file named `settings.json` which contains the filtered settings from the `config.cson` file. Can you share your gist? Or provide more information what you are seeing / expecting? Otherwise it might be difficult to help.

**Comment by r-chris** [comment]
Yes, that appears to be correct, but it appears to be missing some of these settings. I have this added to the end of my `config.cson` for example:

```
config.cson:
[...]
".gfm.source":
  whitespace:
    removeTrailingWhitespace: false
".perl.source":
  whitespace:
removeTrailingWhitespace: false
```

And this is what the `settings.json` looks like:

```
{
	"core": {
		"disabledPackages": [
			[...]
			"git-blame",
			[...]
		]
	},
	"editor": {
		"fontSize": 16,
		"invisibles": {},
		"scrollPastEnd": true,
		"showInvisibles": true,
		"softWrap": true,
		"tabLength": 4
	},
	"exception-reporting": {
		"userId": "[...]"
	},
	"minimap": {
		"plugins": {
			"git-diff": true,
			"git-diffDecorationsZIndex": 0
		}
	},
	"split-diff": {
		"diffWords": true,
		"ignoreWhitespace": true,
		"leftEditorColor": "red",
		"rightEditorColor": "green",
		"syncHorizontalScroll": true
	},
	"sync-settings": {
		"analytics": false,
		"extraFiles": [
			"config.cson"
		],
		"gistDescription": "[...]"
	},
	"tree-view": {
		"hideVcsIgnoredFiles": true
	},
	"welcome": {
		"showOnStartup": false
	},
	"whitespace": {}
}
```

I replaced some irrelevant parts with `[...]` (e.g. disabled packages). You will also see that I added `config.cson` as an `extraFile`, because the above settings where not showing up otherwise.

Is this possible or not recommended ?

**Comment by dirk-thomas** [comment]
I am not sure what happens if two mechanisms backup / restore the same file. I would at least recommend to be very careful with that.

The API [atom.config.settings](https://github.com/atom-community/sync-settings/blob/9098c5a4aa65365b90c5b4d4f98930df6519b199/lib/sync-settings.coffee#L255) returns all the settings under `"*"`. If your additional configuration keys are siblings of `"*"` then they are not visible to the API.

Can you please clarify how you have added these settings? Did you edit the file manually or used some kind of settings UI?

**Comment by dirk-thomas** [comment]
It looks like that the currently used API doesn't access the [language-specific settings](http://flight-manual.atom.io/using-atom/sections/basic-customization/#language-specific-settings-in-your-config-file). I have to figure out what API is able to read these language-specific settings...

**Comment by dirk-thomas** [comment]
It seems there is no API to access this part of the configuration file. I will update the title of this ticket to clarify that the goal is to also sync language-specific settings.

**Comment by r-chris** [comment]
Yes, I added those settings manually as suggested by the [`whitespace`](https://github.com/atom/whitespace) package. Assuming they are using those settings, there should be a way to access them?

**Comment by krzysztof-sikorski** [comment]
There is a simple package called [tab-control](https://atom.io/packages/tab-control) which has an "autosave" option to update language-specific tab settings.

I peeked into its [code](https://github.com/lexicalunit/tab-control/blob/master/lib/tab-control-dialog.coffee#L108), and it seems like one can use language-specific settings by calling config API with additional `scopeSelector` parameter.

**Comment by krzysztof-sikorski** [comment]
Damn. I dug a little deeper and yes, config API accepts an additional "scope" option to get language-specific settings (check [API docs](https://atom.io/docs/api/v1.0.0/Config), the parameter is named differently for get and set methods), **but** I could not find a way to enumerate all possible scopes...

Oh well, that's my "2 cents", now I have to go back to my own work.

**Comment by dirk-thomas** [comment]
I asked on Slack and @lee-dohm suggested to read the file directly. It is not likely that an API for this would be accepted since it is only useful for very few corner cases.

**Comment by pythe** [comment]
This is a feature I'd appreciate as well. Specifically, I set the language-elm package to use 4-space tabs and default to 2-space in all other file types. My config.cson contains these settings:

```cson
"*":
  "language-elm":
      autocompleteEnabled: false
".elm.source":
  editor:
    autoIndentOnPaste: true
    preferredLineLength: 120
    softWrapHangingIndent: 4
    tabLength: 4
```

And as expected from previous discussion here, only the autocompleteEnabled key, as a descendent of "*", is persisted to the gist.

I followed the docs link that Krzysztof provided and found [ScopeDescriptor::getScopesArray()](https://atom.io/docs/api/v1.0.0/ScopeDescriptor#instance-getScopesArray) - is that what we wanted, to enumerate scopes?

**Comment by Undistraction** [comment]
Just got bitten by this as well. Language specific settings were getting written inside the global settings object in the gist.

**Comment by krzysztof-sikorski** [comment]
I just had an idea for a partial workaround: the main problem seems to be that the package needs a list of "scopes" to use as a parameter for fetching and storing the settings... so why not just add a new setting containing a list of scopes to be synced?

The setting could be initialized with a list of frequently-used scopes, or additionally the package could observe editor's "grammar changed" events and update the list with actually-used scopes (although such monitoring might be better suited for a separate "companion" package).

**Comment by Undistraction** [comment]
That's a great idea.

**Comment by dirk-thomas** [comment]
@krzysztof-sikorski Why should the user need to configure this list? In my opinion the goal should be to sync all language specific settings out-of-the-box - same as for the other package settings.

**Comment by Undistraction** [comment]
Obviously that is the ideal result, but if that isn't possible with the
current API, @krzysztof-sikorski's idea offers a workaround which a fix for
the current (broken) implementation.

**Comment by krzysztof-sikorski** [comment]
@dirk-thomas I'll try to elaborate.

I was thinking in terms of what is possible in Atom's API. Language-specific settings can be fetched by supplying an additional "scope" (grammar/language) parameter, but I could not find how to get a list of all possible scopes... but finally I got an idea - why not just store that list explicitly, in a new package setting?

My assumption is that an user would not customize settings for languages that s/he does not actually use. So the package does not need to know a list of all languages supported by Atom but only the languages that are used by that particular user. And these languages can be detected "on the fly" by observing editor's "grammar changed" events, similar to what the above-mentioned `tab-control` extension does.

So the list of "relevant"/to-be-synced languages would grow naturally while Atom is used, and the only problem is initializing the setting after `sync-settings` is installed for the first time. But the user already has to do some manual after-install configuration (Gist ID, token etc) so I think that is not a big issue.

**Comment by dirk-thomas** [comment]
I understand your idea. I still don't think it is reasonable to let the user specify the scope names. Instead I would recommend to read the `config.cson` file just to extract all available scope names and then use the available API to get / set the data within each scope.

**Comment by krzysztof-sikorski** [comment]
Yes, that would work too, sorry for making noise. Please treat my idea as a mental excercise "what is possible using *only* Atom's APIs".

**Comment by omkelderman** [comment]
isnt this basically a dub of #121 now? 😛

**Comment by dirk-thomas** [comment]
@omkelderman Thanks for pointing it out. I closed the other ticket since this one contains more information / discussion.

**Comment by borishere** [comment]
Hi guys.
I still don't understand what should I do to sync language specific settings:) Is it possible or?

**Comment by krzysztof-sikorski** [comment]
@borishere This is not implemented yet. So far there was only a discussion how exactly it could be done.

**Comment by Syphdias** [comment]
Any news on finding all the (language) scopes? The [ScopeDescriptor](https://atom.io/docs/api/v1.0.0/ScopeDescriptor) sounded promising and this sentence from the site sounds like the right thing, so why was it discarded so quickly?
> You can use ScopeDescriptors to get language-specific config settings via [Config::get](https://atom.io/docs/api/v1.0.0/Config#instance-get).

Especially the [instance-getAll](https://atom.io/docs/api/v1.0.0/Config#instance-getAll) in the Extended Methods section sounds promising without knowing too much about the code

**Comment by krzysztof-sikorski** [comment]
@Syphdias I don't remember that method from my previous browsing through Flight Manual, maybe it was added in a recent Atom update. But it still does not help this case, because it needs a setting key as a parameter... so it just shifts the problem to a different place - instead of list of all languages, we need a list of all setting keys.
