### ISSUE TITLE
Allow restore from a public gist without a Github account

### ISSUE THREAD

**Issue by papajohn** [atom-community/sync-settings#290]
I would like to use `sync-settings` to distribute an Atom configuration to students in an intro CS course. It's problematic that to use the package, one needs to:
- create a Github account, 
- set up a personal access token, and 
- create a Gist

It would be ideal if the students could:
- Install atom
- Install `sync-settings`
- Paste in a public Gist of the default settings for the course, then
- Restore settings

Is this alternate workflow something you're interested in supporting, or do you think we would need to fork this package? Thanks!

**Comment by dirk-thomas** [comment]
This is indeed an interesting use case. Currently it is not supported yet but any PR for this is welcome.

I will close this ticket though since the same request is already captures in #281.
