### ISSUE TITLE
"Gist ID Not Found"

### ISSUE THREAD

**Issue by c6y** [atom-community/sync-settings#295]
Hi, I', trying to sync but the package can't find the Gist ID. It's there and I entered it correctly though. Any ideas what I can do? Thanks!

**Comment by c6y** [comment]
Sorry my fault — I forgot to select the scope for the token. Sync works great now. Thanks!

**Comment by Lavenderloved** [comment]
Okay, I have get it settled.I just copy the wrong character string with something wrong character string.Smlie``````
