### ISSUE TITLE
Add option to specify indent size

### ISSUE THREAD

**Issue by dsifford** [atom-community/sync-settings#301]
Hi there,

Love the package; it's been a lifesaver! 

One little request I'd have for a future release is to be able to specify the indent size for `config.cson`. It appears to be set at 2 spaces, but I'd like to have 4.

Thanks for considering 😄 

**Edit:** Also specifying quote character would be nice too!

**Comment by dirk-thomas** [comment]
The file format of the `config.cson` file is not controlled by this package but Atom itself. So I don't think this package can do anything about it.

**Comment by dsifford** [comment]
Ah, didn't know that. Nope, probably nothing you can do then. 

Thanks anyway!
