### ISSUE TITLE
sync-settings: Mandatory settings missing: Gist ID, GitHub personal access token

### ISSUE THREAD

**Issue by Josephx64** [atom-community/sync-settings#302]
Always that I open my Atom I got this message:
sync-settings: Mandatory settings missing: Gist ID, GitHub personal access token

How can I solve this?

**Comment by dirk-thomas** [comment]
Please read the setup instructions: https://github.com/atom-community/sync-settings#setup

**Comment by dirk-thomas** [comment]
I will close this since I assume the instructions resolved the question.
