### ISSUE TITLE
Override Certain Settings?

### ISSUE THREAD

**Issue by entozoon** [atom-community/sync-settings#308]
Hi there, this is by far my favourite atom package by the way!
I was wondering if it's possible to override a setting for a specific machine?
i.e. I'd very much like my linter-phpcs to use a different coding standard at home and at work (yep...)

I know it kinda defeats the point of sync-settings but I imagine others want the same thing and forking would mean the pain of maintaining multiple gists.

**Comment by dirk-thomas** [comment]
It is unclear to me which of two you would then want to be synced to the gist file.

Instead you could just blacklist that specific config key so that single option would stay local and never gets synced to the gist.

**Comment by entozoon** [comment]
Ah, that could do the job! I'll give it a go, thank you very much.

**Comment by entozoon** [comment]
Worked perfectly, thanks again @dirk-thomas 
For future reference, in my **config.cson**, I added this to the relevant section:
```
  "sync-settings":
    blacklistedKeys: [
      "linter-phpcs.codeStandardOrConfigFile"
      "linter-phpcs.executablePath"
    ]
```
