### ISSUE TITLE
Sync-settings has no configuration option

### ISSUE THREAD

**Issue by ceres629** [atom-community/sync-settings#313]
One of the steps mentions:
3. Copy the access token to Sync Settings configuration.

There doesn't seem to be any settings button and nowhere to input it. 
Am I missing something here?
![pic](https://cloud.githubusercontent.com/assets/6934394/20098535/483e579c-a5ac-11e6-8df6-e3a1f3b67b34.png)

**Comment by dirk-thomas** [comment]
There should indeed be a `Settings` button left beside uninstall. It looks like a quirk with the package installation in Atom. You might want to try uninstalling and reinstalling the package and/or restarting Atom. Hopefully that helps.

**Comment by dirk-thomas** [comment]
I will close the ticket for now since I assume the problem was resolved with the above suggestion.
