### ISSUE TITLE
Option to review and merge settings on startup

### ISSUE THREAD

**Issue by mateddy** [atom-community/sync-settings#314]
I ran atom on two machines and made settings before I discovered sync-settings.

For the first time of sync, I have to select the settings manually.  Is it possible to review and merge the differences in atom, before backup a new setting?

**Comment by dirk-thomas** [comment]
The package does not support to "merge" configuration. A `restore` only overwrites existing configuration options but doesn't remove options which are not in the gist.

The existing ticket #18 covers the case of seeing the difference between the local config and an existing gist. This would allow you to manually merge the desired settings.
