### ISSUE TITLE
sync status message

### ISSUE THREAD

**Issue by ubergeekzone** [atom-community/sync-settings#316]
having a message saying the status of the sync would be awesome, right now it shows nothing.

**Comment by dirk-thomas** [comment]
Are you referring to the case when triggering a restore? That should be covered by #311. If not, can you please elaborate when you are expecting a message.

**Comment by ubergeekzone** [comment]
yes, #311 how would i go about installing that?

**Comment by dirk-thomas** [comment]
Until it is merged and released you would need to clone the repo with the branch of that PR, install the node dependencies manually and link it into your Atom package folder.

**Comment by ubergeekzone** [comment]
thanks @dirk-thomas when will this be in the master build? I was able to get it working by installing the node modules and then copying the folder into atom packages dir. works great. Why not released yet?

**Comment by dirk-thomas** [comment]
It is just about finding time to test and ensure it doesn't break anything.

**Comment by ubergeekzone** [comment]
@dirk-thomas understood. working great on macOS

**Comment by dirk-thomas** [comment]
That is always good to know. Thank you for the feedback. I will try to get it out in the near future.
