### ISSUE TITLE
Store auth token in separate file

### ISSUE THREAD

**Issue by stefanorg** [atom-community/sync-settings#318]
Hi,
i'm using dotfiles, and the atom dir is committed to my github dotfiles!
Github, for security reason, don't allow committing accessTokens in public repos. How can i use gistId and personalAccessToken avoid to commit it to my repo?

**Comment by dirk-thomas** [comment]
Currently Atom doesn't provide a nice way to store these tokens outside of the config file. Until that is provided every package would need to come up with a custom solution.

**Comment by stefanorg** [comment]
the `Blacklisted Keys` settings parameters is intended for what?

**Comment by stefanorg** [comment]
this is not make sense?

```
"sync-settings":
    _analyticsUserId: "cac92d12-fae3-4e8a-9c95-eb858f857744"
    _lastBackupHash: "3d3c8fa7cf45c06b68c33e3be28c712a8f368dee"
    analytics: false
    blacklistedKeys: [
      "sync-settings.gistId"
      "sync-settings.personalAccessToken"
    ]
```

**Comment by dirk-thomas** [comment]
A few configuration keys are always implicitly blacklisted (see https://github.com/atom-community/sync-settings/blob/cd58f243f930906e1b75b1786f359c1197cada28/lib/sync-settings.coffee#L10-L15). These blacklisted keys will not be put into the Gist.

**Comment by stefanorg** [comment]
ok thanks

**Comment by UziTech** [comment]
You can keep your auth token and gist id in environment variables `GITHUB_TOKEN` and `GIST_ID`
