### ISSUE TITLE
Segment over quota

### ISSUE THREAD

**Issue by groupsky** [atom-community/sync-settings#321]
I just received a friendly email from segment, that we are 1806% over the free quota and they suggest to move to paid plan around $240 per month.

According to #82 segment service is used to keep track of installed versions and some basic analytics. IMHO it's not worth paying for that service so we have until **15th december** to come up with alternative solution or lower the usage.

Here is the full email:

> Hi Geno ,
> 
> As a part of an annual audit, we've found that your account, Sync Settings for Atom , is not compliant with Segment's usage terms. (You are 1806% over your quota, see below.)
> 
> I would love to let you continue to use Segment on your current plan, however, given your current usage this isn't possible.
> 
> We don't have a credit card on file for your account, so please [log in here](http://email.segment.com/e/c/eyJlbWFpbF9pZCI6Ik5UTTJPVGs2RndHN3NnSmtBQUp6QUJZZjJob0JWakFtRXNjVlNoaFlQMGNBQVcwNk16UTNPVFV4QUE9PSIsInBvc2l0aW9uIjowLCJocmVmIjoiaHR0cHM6Ly9zZWdtZW50LmNvbS9cbmF0b20tc3luYy1zZXR0aW5nc1xuXG4vc2V0dGluZ3MvYmlsbGluZyJ9/380395134d06b7ee4ddd64ef387570af3b826ebe14c9925b4f10940ac0bbe18a) and add a valid credit card, so we can process the charge and upgrade you to the new plan.(You can expect $240 based on your current usage.)
> You will be moved to the [Team plan](http://email.segment.com/e/c/eyJlbWFpbF9pZCI6Ik5UTTJPVGs2RndHN3NnSmtBQUp6QUJZZjJob0JWakFtRXNjVlNoaFlQMGNBQVcwNk16UTNPVFV4QUE9PSIsInBvc2l0aW9uIjoxLCJocmVmIjoiaHR0cHM6Ly9zZWdtZW50LmNvbS9wcmljaW5nIiwibGlua19pZCI6MTczNDUzMzR9/6714f3f0406a6d442fc1d7b839a93e4a833ba327b615fd0fa88d6d9ca4e193ad) which allows you to use unlimited integrations and sources. It also includes a warehouse. The plan is based on monthly tracked users, that better scales with our customers' growth than API calls.
> 
> **I strongly suggest that you add a credit card to your account by December 15. If not, unfortunately you and your team will no longer have access to Sync Settings for Atom 's Segment account.**
> 
> Regards,
> 
> Hannah Russell-Goodson
> Customer Success @ Segment
> 
> ---------- Forwarded message --------- 
> From: Segment Billing < billing@segment.com> 
> Date: Wed, November 30, 2016 at 11:26 
> Subject: Account Sync Settings for Atom is exceeding current plan limits 
> To: \<Hannah Russell-Goodson> 
>> Customer Sync Settings for Atom is exceeding current plan limits by 1806% 
>> * Billing email: geno@roupsky.name
>> * First user name & email: Geno Roupsky - geno@roupsky.name
>> * Workspace id / slug: atom-sync-settings / Ce4CgBfTxn
>> * Current plan name: Integrations Developer
>> * Current plan API quota: 50000
>> * API call usage, 30 day period: 903362
>> * API calls over quota, 30 day period: 853,362 - 1806%
>> * Last paid amount: $0
>> * MTU count, 30 day period: 24660
>> * Suggested plan name: Team
>> * Updated Price (monthly): $240

**Comment by jerone** [comment]
Damn. I don't see the real benefit for tracking usage, I'm :+1: on removing the logging all together.

If other agree, @dirk-thomas, do you have time for that?

**Comment by groupsky** [comment]
Since I'm not actively involved with the project, I don't have a strong word here, but IMHO some statistics is nice to have. At least when we implemented this feature the main idea was to keep track of used version, so in case of breaking changes to have real data for evaluation. 

A possible alternative is to switch to sentry - I think I can provide a hosted solution so that we don't have problem with hitting the free tier limits.

Another solution could be to track once a day/week to reduce the traffic and keep within free tier.

**Comment by jerone** [comment]
I haven't been contributing to this project (@dirk-thomas is doing a good job) and kinda have moved on to other projects (still using this package daily), so I don't use the statistics.

> A possible alternative is to switch to sentry - I think I can provide a hosted solution so that we don't have problem with hitting the free tier limits.

If you are willing to spend the time and money; great. 
Another solution might be to just push it to Google Analytics without third-party tunnel.

> Another solution could be to track once a day/week to reduce the traffic and keep within free tier.

Do you think they are open to that? From the mail it doesn't looks like it, as the "damage" (1800%) is already done.

**Comment by dirk-thomas** [comment]
I haven't seen these statistics so it is difficult for me to make a decision if it makes sense. How can I get access to the already collected data?

**Comment by jerone** [comment]
@dirk-thomas I send you an invitation to your mail.

**Comment by dirk-thomas** [comment]
Thanks for giving me access. I looked into the stats and logged information a bit. Only to have data about the version being used is imo not justifying this data collection effort. Or has anybody in the recent past looked at the statistics at all?

I think in case of potential regressions users are doing a great job of reporting issues. And from past reports it seems that users also keep their packages pretty up-to-date. It is rather uncommon to get tickets for older versions.

Therefore I would be in favor of removing the analytics / tracker integration. I am happy to create a PR for that (but would like to merge #320 before - first fix the feature, then remove it :wink:).

**Comment by jerone** [comment]
> Only to have data about the version being used is imo not justifying this data collection effort. Or has anybody in the recent past looked at the statistics at all?

What we are tracking is which actions are being executed (Activate, Backup, Check backup, Deactivate, Restore, View backup) with values of Atom version, package version, platform and useragent (which should not contain any differences). Aldo I've not been able to filter out those data in GA, I can see the amount of traffic (active users) and their demographics etc...

> I think in case of potential regressions users are doing a great job of reporting issues. And from past reports it seems that users also keep their packages pretty up-to-date. It is rather uncommon to get tickets for older versions.

I agree.

My suggestion would be to remove the whole thing or keep a simple connection with GA directly (active users only).

**Comment by dirk-thomas** [comment]
Please see #322 for removing the analytics part from this package.

**Comment by dirk-thomas** [comment]
I have merged the PR which removes the analytics part and also released a new version (0.8.0) of the package.

I would wait until after Dec 15th and see what happens with the remaining older installations when Segment shuts down the account. Afterwards it might be good if someone who has access to that account disables / closes the account somehow.

**Comment by jerone** [comment]
Oh sorry. Forgot about this. Like I said earlier; I'm fine with removing the analytics. So good job on removing the logic.
