### ISSUE TITLE
Error backing up your settings: <!DOCTYPE html>

### ISSUE THREAD

**Issue by Xkeeper0** [atom-community/sync-settings#324]
I installed this package and tried to configure it. I created the personal access token as described with "gist" permission, then created a secret Gist containing just "X". I pasted the personal access token into the config, copied the gist ID into it, and tried using "Synchronize Settings -> Backup". I get an error message (the one in the title), and checking the developer console shows that it's getting back an error HTML page with a 400 response code.

I do not know what to do from this point. I have verified the key is copied correctly (but GitHub says they have not been used), I checked that the Gist ID was correct, but nothing seems to work.

Edit: I tried using a different (public) Gist, and using the command palette instead of the menu option, but I get the same error in either case.

![image](https://cloud.githubusercontent.com/assets/1077535/21076608/a5d4ed98-bee4-11e6-9107-16d494685fb4.png)

![image](https://cloud.githubusercontent.com/assets/1077535/21076622/edd4ab42-bee4-11e6-9fde-7cff826e2349.png)

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
