### ISSUE TITLE
Show offline message instead of error

### ISSUE THREAD

**Issue by BarryThePenguin** [atom-community/sync-settings#326]
Just opened atom now while not connected to the internet. sync-settings shows an error message (ENOTFOUND)  getaddrinfo. This is fine

Would it be worth detecting online status and showing that instead?

**Comment by dirk-thomas** [comment]
That would indeed be nice. Do you know if Atom has any API for that already and would like to contribute a PR to add this enhancement?

**Comment by BarryThePenguin** [comment]
I'm assuming we'll have access to `window.navigator`. There's a tutorial on offline/online events in the electron docs http://electron.atom.io/docs/tutorial/online-offline-events/

Happy to put together a PR 😄

**Comment by UziTech** [comment]
I believe this was fixed in v4.2.0
