### ISSUE TITLE
Restore keeps reinstalling packages

### ISSUE THREAD

**Issue by github-sjacobs** [atom-community/sync-settings#328]
After performing a backup or after restarting atom, when performing a restore I am seeing 25 packages installed. If I do the restore again it says everything is up to date. Closing and restarting atom results in the same re installation. I have seen this on both Linux and Windows.

sync-settings 0.8.0
atom 1.12.7
centos 7.1
Windows 7

**Comment by github-sjacobs** [comment]
I can confirm that the packages that are reinstalled as I described are disabled. As to whether or not this is the same issue as 310 or not I couldn’t say.

**Comment by dirk-thomas** [comment]
I have created #329 which should address the problem of trying to install packages which are disabled but present. It would be great if you could try the package from that branch and confirm if it fixes the problem for you.

**Comment by github-sjacobs** [comment]
I would be happy to if you tell me how to do this.

**Comment by dirk-thomas** [comment]
I don't have a link at hand which contains a nice description how to do that. We will see if the following instructions work for you: This thread (https://discuss.atom.io/t/load-developing-package/2554) describes how to get the development version of a package installed (`apm develop ...`) and using it (`atom -d`). Between those two commands you need to switch to the branch of the PR #329 (`fix_restore_disabled`) as described in this thread (https://discuss.atom.io/t/install-package-from-a-specific-github-branch/35537).

**Comment by github-sjacobs** [comment]
I had some help to get this done and I tested it. It is no longer updating all those disabled packages. Looks like it is fixed to me.

**Comment by dirk-thomas** [comment]
Great, thank you for the initial report and the confirmation. I will go ahead and merge the patch as well as release a new minor version.
