### ISSUE TITLE
init.js file not synced

### ISSUE THREAD

**Issue by bdougherty** [atom-community/sync-settings#331]
I use an `init.js` file instead of coffeescript and this package doesn't seem to recognize it. I can add it to the extra files, but I think since it is a valid file for Atom, it should be synced.

**Comment by dirk-thomas** [comment]
I don't understand your use case yet. What is the `init.js` file used for? Where is it located? What does it contain?

**Comment by bdougherty** [comment]
It is the same as the init.cofee file, except it is JS and not CoffeeScript.

http://flight-manual.atom.io/hacking-atom/sections/the-init-file/

**Comment by dirk-thomas** [comment]
Thanks for clarifying. Related line of code currently only handling `init.coffee`: https://github.com/atom-community/sync-settings/blob/538b24c89096bb168a189838338f670a55bd64f2/lib/sync-settings.coffee#L151

**Comment by jrop** [comment]
@dirk-thomas I have a pull request open that would fix this. Are you able to review it?

**Comment by dirk-thomas** [comment]
As soon as I find some time I will try the PR and comment / merge it.

**Comment by saadq** [comment]
Related issue: There is a similar problem when using `keymap.json` and `snippets.json` instead of using `keymap.cson` and `snippets.cson`.
