### ISSUE TITLE
Is there a way how to suppress notification popup on every sync?

### ISSUE THREAD

**Issue by crudo** [atom-community/sync-settings#336]

**Comment by dirk-thomas** [comment]
Are you referring to the automatic checking of the latest backup which then shows the message "Latest backup is already applied"? Yes, the last option in the settings of this package "Quiet update check" mutes this notification messages.

If this is not the notification you are referring to can you please clarify the message in the popup. And if you triggered a command manually for this to happen.

**Comment by crudo** [comment]
Thanks!
