### ISSUE TITLE
Clean up old package settings

### ISSUE THREAD

**Issue by ryanaltvater** [atom-community/sync-settings#337]
I couldn't find an open/closed issue related to my question. I was wondering if it's possible to have an option for **sync-settings** to clean up old settings from uninstalled packages. I say an option because some might like that their old settings aren't removed in case they come back to a package later on and their settings are restored. Personally, if I remove a package it's because I'm not going to use it again. Otherwise, I'll just disable it for later. I was going through my Gist and noticed old package settings that I haven't had installed in over a year. So I removed them manually. I found a username and some API keys just sitting out there under some older package settings.

**Comment by dirk-thomas** [comment]
While this feature idea sounds interesting I would consider it to be orthogonal to this package. A command to remove all settings of not (anymore) installed packages would be useful even when not using `sync-settings`. Therefore I am inclined to recommend implementing such a feature in a separate package.
