### ISSUE TITLE
sync settings simply does not for me at all

### ISSUE THREAD

**Issue by leurcutis** [atom-community/sync-settings#344]
followed all the steps -

access token generated
gist created

access token added
gist id added

atom restarted

I get yellow banner message - backed up

followed same instructions on second machine, no dice.

I get all the messaging and behavior of the app that suggests that it is trying to work, but it is not syncing packages between my two machines.

**Comment by dirk-thomas** [comment]
You don't mention in your steps that you have invoked the `restore` command. So I assume you have only triggered the `backup` command on both machines.

If both machines use the same Gist ID you need to trigger `backup` on one machine and then `restore` on a second to fetch and apply the configuration which was stored in the Gist by the first machine.

**Comment by dirk-thomas** [comment]
I will close this for now. Please feel free to provide more information if this is still a problem.
