### ISSUE TITLE
Need setup help

### ISSUE THREAD

**Issue by anthonyalvarez** [atom-community/sync-settings#346]
Created a Personal access tokens and pasted it into Atom's settings. 
Where or how is a Gist ID created?
Is Gist ID the filename of the Gist?
Having problems following synch-settings' setup instructions. 
Any help appreciated,

Thank you.

**Comment by dirk-thomas** [comment]
The setup instructions guide you through the process: https://github.com/atom-community/sync-settings#setup

If you have any problems following them please describe the exact steps you have tried and what the problem / question is. (I think you can choose an arbitrary filename for the new Gist.)
