### ISSUE TITLE
Show invisibles in global settings not restored properly

### ISSUE THREAD

**Issue by augustobmoura** [atom-community/sync-settings#348]
I don't no if it occurs with others settings. When disabling the Show Invisibles option the Atom editor doesn't write it as false, instead it removes it from config.cson. Because of that when the backup is restored, the option (if true in the client and false in the backup) isn't enforced.

**Comment by dirk-thomas** [comment]
The package works in a way that it only sets the settings available in your backup. It doesn't remove existing settings which are not part your backup. In this case this is clearly not working as you would expect it to. To address this the package needs to change how the settings are restored (allowing to remove other local settings).

**Comment by borishere** [comment]
Many settings are stored in the way @augusto-moura mentioned above. That makes sync-settings not so useful:( Need to be fixed somehow.

**Comment by gronemeier** [comment]
I just stumbled across this issue and did a bit of investigation.
If you have `showInvisibles: false` actually written in your `config.cson` file while making a backup, the setting actually appears within your backup.
If you now for some reason change your local setting to `true` and then make a restore, your backed-up setting will set it to false. As this is the default value of `showInvisibles`, it is then somehow removed from your `config.cson` file.

So, my suggested work-around would be:
Make sure that your setting does actually appear within your config when making a backup. Then this will be enforced when restoring it again from your gist.
However, the problem then again arises when you try to update your backup... So it is still a bug which needs to be fixed ;-)
