### ISSUE TITLE
Support gists stored on Github Enterprise

### ISSUE THREAD

**Issue by woneill** [atom-community/sync-settings#349]
It'd be a nice feature to make the gist URL configurable so that settings could be stored on Github Enterprise. Then it could be used to provide a standardized config for an organization.

**Comment by dirk-thomas** [comment]
Please consider to provide a PR to support this use case. The custom URL needs to be provided in two location as far as I can see:
* https://github.com/atom-community/sync-settings/blob/a8fe7a74af343d7e58ff459c9b2e981eeb6f9369/lib/sync-settings.coffee#L259-L262
* https://github.com/atom-community/sync-settings/blob/a8fe7a74af343d7e58ff459c9b2e981eeb6f9369/lib/sync-settings.coffee#L186

**Comment by woneill** [comment]
I no longer have access to a Github Enterprise instance so I wouldn't be able to test this anymore. Leaving this open in case someone else could use this and is able to make a testable PR

**Comment by uchuugaka** [comment]
I'd be interested as I have Github Enterprise. Any pointers where to look? I would envision a default github.com url but ability to back up to one github enterprise URL, so really just a field with a default value, exposing the URL.

**Comment by dirk-thomas** [comment]
You can add a config value to the package settings which defaults to the currently used URL. And in the two locations mentioned above it should use the config value instead of the hardcoded one instead.

**Comment by UziTech** [comment]
With the new [Location Service](https://github.com/atom-community/sync-settings#location-service) you could create a package that does this. If you need any help creating the location service package let me know.
