### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, open '$ATOM_HOME/packages'

### ISSUE THREAD

**Issue by GeorgeWL** [atom-community/sync-settings#352]
[Enter steps to reproduce:]

1. Complete uninstall by deleting all atom folders from system due to an issue with a failed atom update.
2. Reinstall atom
3. Install atom-sync-settings
4. add token & [gist id](https://gist.github.com/GeorgeWL/e833d23f5c7b094778766b5414fc2129)  
5. packages toolbar menu > sync-settings > restore
6. Fails and throws error.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.1

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, open 'C:\Users\georg\.atom\packages'

```
At fs.js:640

Error: EISDIR: illegal operation on a directory, open 'C:\Users\georg\.atom\packages'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at /packages/sync-settings/lib/sync-settings.coffee:248:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:10.4.0 core:confirm (input.hidden-input)
  2x -2:15.9.0 core:paste (input.hidden-input)
     -0:33.9.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
sync-settings 0.8.1 
```

**Comment by dirk-thomas** [comment]
You gist contains a file name `packages` which can't be restored since a folder with the same name existing in your Atom home. I don't know how you created the Gist but you can remove that empty file from the Gist and the restore should work.

**Comment by GeorgeWL** [comment]
I created the gist using the standard way stated in the guide. 
alright, shall remove it.

**Comment by dirk-thomas** [comment]
When you created the Gist you might have named the empty file `packages`? That could be reason for the collision.

**Comment by dirk-thomas** [comment]
Can you please try to reproduce the problem and comment here about it. I created #353 to clarify which filename should be used (it basically doesn't matter which filename you use as long as it doesn't collide with any files / folders in the Atom home).

**Comment by GeorgeWL** [comment]
it's exactly as you said,  I called the file the same name as one in atom folders.

**Comment by dirk-thomas** [comment]
Thanks for reporting. The updates instructions should avoid that users run into this in the future.
