### ISSUE TITLE
Always loosing token and gist id

### ISSUE THREAD

**Issue by rlam3** [atom-community/sync-settings#355]
Always loosing token and gist id. Any reason why this is happening? Is it because after atom updates..?

**Comment by dirk-thomas** [comment]
Please provide more information in order to reproduce the problem. What exact version of Atom and packages are you using? What platform are you on? What are the exact steps you are doing?

**Comment by dirk-thomas** [comment]
I will close this for now due to lack of response. Please feel free to comment with the requested information and the ticket can be reopened.
