### ISSUE TITLE
Broken settings on restore when using a . in property names

### ISSUE THREAD

**Issue by jpeltoniemi** [atom-community/sync-settings#358]
The restored settings for package [file-types](https://github.com/execjosh/atom-file-types) may break when restoring settings.

config.cson:
```
  "file-types":
    html: "text.html.js"
    "^[^\\.]+$": "source.shell"            (A: Original regex, doesn't work)
    "^[\\w\\d\\-_]+$": "source.shell"      (B: New regex, works)
```

File-types tries to set proper syntax hilighting according to filename matching rules above.

I previously used regex A to match filenames without a dot but realised sync-settings(or Atom) has a special meaning for dot in property names.

I'm not sure if this is a bug or just how Atom works, but I'm reporting it just in case. I'm also creating an issue to file-types and referencing this one there.

**Comment by dirk-thomas** [comment]
#424 should address this problem.
