### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by MDCEY** [atom-community/sync-settings#359]
I'm trying to stay in sync between home and work.

I've added a proxy line in the code to reach my proxy but it's failing on local issuer certificate.

I have tried the strictssl = false in apm and still not working.
disabling strict ssl workins on git

here's the error

sync-settings: Error retrieving your settings. (unable to get local issuer certificate

Sorry for formatting, on mobile

**Comment by k33k00** [comment]
Just seen #270 looks like it may be a similar request

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this feature.

**Comment by K4zuki** [comment]
@k33k00 
I had same error on `atom=1.18.0` but backward install down to `1.14.0` worked.

**`1.15.0` was NG for both 32/64 bit binaries**

I am not sure if this solution works with proxy but downgrade install of atom is worth a try for you too.

@dirk-thomas 
If you know anything, is there any change related to SSL between `atom=1.14.0` and `1.15.0`?

**Comment by dirk-thomas** [comment]
> If you know anything, is there any change related to SSL between atom=1.14.3 and 1.15.0?

Sorry, I don't know anything about it.

**Comment by UziTech** [comment]
duplicate of #270
