### ISSUE TITLE
Uncaught SyntaxError: Unexpected token / in JSON at position 0

### ISSUE THREAD

**Issue by CarlosRGL** [atom-community/sync-settings#362]
[Enter steps to reproduce:]

1. trying to restore backup at fresh install

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.1

### Stack Trace

Uncaught SyntaxError: Unexpected token / in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected token / in JSON at position 0
    at Object.parse (native)
    at /packages/sync-settings/lib/sync-settings.coffee:229:37
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:08.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
sync-settings 0.8.1 
```

**Comment by dirk-thomas** [comment]
The error message indicates that the Gist you are trying to restore from (specifically the file `settings.json`) doesn't contain valid JSON code. Can you please check your Gist / share the link to make sure it is valid.

**Comment by CarlosRGL** [comment]
my fault.. bad syntax.

thx for rapid answer!
