### ISSUE TITLE
[Suggestion] Use Busy-signal to show sync status instead of notifications

### ISSUE THREAD

**Issue by jonyeezs** [atom-community/sync-settings#364]
Qualms with the toaster:
It does get abit noisy on the screen.
Most of the time i don't care if its running.

An icon on the status bar would be good enough for me to look at.

**When** I restore /or backup
**Then** I want to see the busy-signal icon spin
**When** the sync process complete
**Then** the icon should stop spinning.

The logs of sync-setting should be in the busy-signal popup.

[This is the api for busy-signal](https://github.com/steelbrain/busy-signal/wiki/Busy-Signal-API)

> Busy Signal is a base package that provides an easy to use API to show your package is performing a task.

**Comment by dirk-thomas** [comment]
That would indeed be a great improvement. Please consider to contribute a pull request for this new feature.

**Comment by jonyeezs** [comment]
ok...so i found out there's another status icon pkg: [busy-signal](https://github.com/noseglid/atom-busy).

and man looks like no one is going to budge to move to the other.

I don't want to start work on this when suddenly majority of the users prefer `atom-busy`.

Let see how many others would like this feature.

What your thoughts?

**Comment by jonyeezs** [comment]
@noseglid has stepped up and moved his biggest atom package `atom-build` to `busy-signal`.
https://github.com/noseglid/atom-build/issues/528

Suffice to say busy-signal is the way to go.

I think some sort of toaster would still be needed to indicate the start and the restart to indicate completion.

All installations should be hidden inside the spinner.
