### ISSUE TITLE
error backing up data: Not Found

### ISSUE THREAD

**Issue by mwilliammyers** [atom-community/sync-settings#366]
After updating to the latest version I received this error:
```
sync-settings.coffee [sm]:173 error backing up data: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"} exports.HttpErrorcode: 404

headers: Objectaccess-control-allow-origin: "*"access-control-expose-headers: "ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"connection: "close"content-length: "96"content-security-policy: "default-src 'none'"content-type: "application/json; charset=utf-8"date: "Fri, 16 Jun 2017 16:54:24 GMT"server: "GitHub.com"status: "404 Not Found"strict-transport-security: "max-age=31536000; includeSubdomains; preload"x-accepted-oauth-scopes: ""x-content-type-options: "nosniff"x-frame-options: "deny"x-github-media-type: "github.v3; format=json"x-github-request-id: "0DD3:2C5B5:2F62:3819:59440D3F"x-oauth-scopes: "repo"x-ratelimit-limit: "5000"x-ratelimit-remaining: "4979"x-ratelimit-reset: "1497634672"x-runtime-rack: "0.020296"x-xss-protection: "1; mode=block"

__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()message: "{"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}"status: "Not Found"

__proto__: Errorconstructor: (message, code, headers)toJSON: ()toString: ()__proto__: Object

(anonymous) @ sync-settings.coffee [sm]:173

sendError @ ~/.config/atom/packages/sync-settings/node_modules/github/lib/index.js:785

(anonymous) @ ~/.config/atom/packages/sync-settings/node_modules/github/lib/index.js:792

callCallback @ ~/.config/atom/packages/sync-settings/node_modules/github/lib/index.js:667

(anonymous) @ ~/.config/atom/packages/sync-settings/node_modules/github/lib/index.js:723

emitNone @ events.js:91

emit @ events.js:185

endReadableNT @ _stream_readable.js:974

_combinedTickCallback @ internal/process/next_tick.js:74

_tickCallback @ internal/process/next_tick.js:98
```

the error that pops up as a GUI notification says:

```
sync-settings: Error backing up your settings. (Gist ID Not Found)
```

things I have already tried to resolve it:
- the easy things like switching wireless networks, uninstalling and reinstalling sync-settings etc.
- created a new (public) gist [here](https://gist.github.com/mwilliammyers/26b15b9a98132e36297d9663a8b33057) according to the [setup](https://github.com/atom-community/sync-settings#setup) instructions, which the `sync-settings:view backup` command opens successfully
- created a new GitHub personal access token
- verified the settings look correct in `config.cson`:
```coffeescript
"sync-settings":
    checkForUpdatedBackup: false
    gistId: "26b15b9a98132e36297d9663a8b33057"
    personalAccessToken: "..."
    quietUpdateCheck: true
```

I am using:
```
Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
It has been working on `atom-beta` for a while now but I guess I could switch to stable if you think it is that...

Any ideas? 

Thanks for your help.

**Comment by dirk-thomas** [comment]
The http errorc ode 404 indicates that the url / gist you are using doesn't exist (hence the error message: "Gist ID Not Found").

I am using the Atom 1.18 beta 3 atm with no problems.

**Comment by mwilliammyers** [comment]
It does exist.

> - created a new (public) gist [here](https://gist.github.com/mwilliammyers/26b15b9a98132e36297d9663a8b33057) according to the [setup](https://github.com/atom-community/sync-settings#setup) instructions, which the `sync-settings:view backup` command opens successfully

**Comment by thibautsacreste** [comment]
I'm experiencing the same issue. Everything used to work up until about a week ago. Gist ([here](https://gist.github.com/thibautsacreste/79b5931464c70b06409eaece91db67d2)) and access token exist. I'm now on Atom 1.18.0 but it had stopped working even before I upgraded.
The `Restore`, `View Backup` and `Check Backup` commands work. The `Backup` command returns the error previously described: `Error backing up your settings. (Gist ID Not Found)`

**Comment by mwilliammyers** [comment]
I looked at this again today and figured it out. The token from settings was shadowed by my environment variable `GITHUB_TOKEN` for a different application which didn't have gist permissions which is being checked at [lib/sync-settings.coffee#L53](https://github.com/atom-community/sync-settings/blob/e3b398419cff185142e26534028a023e5513df72/lib/sync-settings.coffee#L53) which was added in 9654b33 

Personally I think it makes more sense to have the `sync-settings` specific override `GITHUB_TOKEN`?

**Comment by subblue** [comment]
Thanks for the insight @mwilliammyers I was having exactly the same issue!

**Comment by dirk-thomas** [comment]
Thank you for investigating this. It makes sense that the settings are being checked before the environment variable. The settings are specific to this package while the environment variable is shared for multiple use cases. I created #374 to reverse the lookup order.

**Comment by mwilliammyers** [comment]
@subblue No problem! Glad I could help.
@dirk-thomas Thanks for the PR. I am good to close the issue if you are. Or did you want to wait until the PR is merged?

**Comment by dirk-thomas** [comment]
This issue will automatically get closed when the PR is being merged.
