### ISSUE TITLE
Option only to sync Community Packages

### ISSUE THREAD

**Issue by DJviolin** [atom-community/sync-settings#37]
It would be nice to have an option when you can only sync the Community Packages. The Gist file here in Github will be much nicer.

**Comment by nelson6e65** [comment]
:+1:

**Comment by mrmckeb** [comment]
Agreed ;)

**Comment by edwinksl** [comment]
:+1:

**Comment by mingelz** [comment]
2 years...

**Comment by dirk-thomas** [comment]
@mingelz Please feel free to contribute and provide a pull request for this feature idea. I am sure the users of this package would appreciate your work :wink:

**Comment by DJviolin** [comment]
I'm no longer feel this necessary, because now we have VScode, which is (don't judge me) much better than Atom. I made the switch, performance wise I feel comparable to Sublime Text, I highly recommend it.

**Comment by IronSavior** [comment]
Why would you want to do this?

**Comment by UziTech** [comment]
Since core packages get installed with Atom there is no reason to list them as installed since they are always installed.
