### ISSUE TITLE
Allow syncing of subfolders

### ISSUE THREAD

**Issue by martin2250** [atom-community/sync-settings#372]
when adding files to 'extra files' that have a forward slash in them, github's server rejects the gist.
I tried replacing slashes with some other char sequence like so
`files[file.replace(/\//g, '+++')]`
([here](https://github.com/atom-community/sync-settings/blob/master/lib/sync-settings.coffee#L164)) which worked, though I'm not sure how this will work on other systems.

I'd love to see this implemented properly

**Comment by ddirks** [comment]
Just a use case for this enhancement: I use the file-templates package, which stores templates as individual files in a subdirectory of the .atom directory. It would be very convenient if sync-settings were able to synchronize this subdirectory across Atom installations.

**Comment by UziTech** [comment]
PRs are welcome

**Comment by UziTech** [comment]
This should be fixed in v2.3.0

**Comment by UziTech** [comment]
this should be fixed in v2.3.0
