### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead

### ISSUE THREAD

**Issue by shangguanfch** [atom-community/sync-settings#376]
Installing “sync-settings@0.8.2” failed.Hide output…
(node:11169) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Request for package information failed: connect ETIMEDOUT 50.16.204.0:443 (5 attempts) (ETIMEDOUT)

**Comment by dirk-thomas** [comment]
I don't see any usage of `os.tmpDir` in this package (see [search](https://github.com/atom-community/sync-settings/search?q=tmpDir)). Therefore I will close this issue for now.

Please feel free to provide more information where the usage should be (preferably with a PR) and this can be reopened.

**Comment by shangguanfch** [comment]
Sorry to bother you. It seems because I use old package. This package is out of date: https://www.archlinux.org/packages/community/x86_64/atom/
