### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by LiguidCool** [atom-community/sync-settings#378]
Hi.
Cant save Token and Gist ID.
1) I run Atom
2) Open plugin configuration
3) Paste token and id
4) click 'Backup' in plugin. Settings added to Gist (i see it). Profit ...
After restart Atom plugin don't see token and id again.  _GOTO 2;_

**Comment by dirk-thomas** [comment]
The `Sync Settings: Backup` command doesn't change any local settings and only creates / updates the gist.

Can you please clarify what you mean with:

> click 'Backup' in plugin

**Comment by LiguidCool** [comment]
Lastest update (0.8.2) fixed the problem.
Thanks!

**Comment by dirk-thomas** [comment]
@LiguidCool I assume you mean version 0.8.3 which was released yesterday?

Anyway I will close this since it is fixed for you.
