### ISSUE TITLE
Long startup because socket hang up

### ISSUE THREAD

**Issue by trippinCode** [atom-community/sync-settings#380]
atom -v
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm list
Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.5
├── one-light-ui@1.10.5
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1 (disabled)
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.107.0
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4 (disabled)
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1 (disabled)
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1 (disabled)
├── language-ruby-on-rails@0.25.2 (disabled)
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0 (disabled)

Community Packages (78) C:\Users\l.schuster\.atom\packages
├── activate-power-mode@2.4.0 (disabled)
├── aligner@1.2.4
├── aligner-css@1.2.1
├── aligner-javascript@1.3.0
├── aligner-php@1.1.1
├── aligner-python@1.1.0
├── aligner-scss@1.3.1
├── atom-autocomplete-php@0.25.6
├── atom-bracket-highlight@0.3.2
├── atom-clock@0.1.14
├── autocomplete-clang@0.11.3
├── autocomplete-php@0.3.7
├── autocomplete-python@1.10.2
├── browser-plus@0.0.98
├── busy-signal@1.4.3
├── clip-history@0.4.0
├── code-peek@1.4.21 (disabled)
├── codelf@8.13.0
├── color-picker@2.2.5
├── critique@0.0.0 (disabled)
├── dash-syntax@0.3.0
├── dash-ui@0.4.2
├── declarations@1.1.3
├── docblockr@0.11.0
├── drunken-php@0.2.3
├── editor-stats@0.17.0
├── emmet@2.4.3 (disabled)
├── emoji-syntax@1.7.2
├── figlet@0.5.4
├── fold-navigator@0.0.620 (disabled)
├── gloom@0.6.4
├── go-plus@5.5.5
├── go-signature-statusbar@1.2.2 (disabled)
├── hey-pane@1.0.0
├── hyperclick@0.1.3
├── icon-fonts@2.16.3
├── imdone-atom@2.2.6
├── intentions@1.1.5
├── intentions-colorpicker@1.0.1
├── jira-issue-search@1.0.3 (disabled)
├── language-docker@1.1.8
├── linter@2.2.0
├── linter-alex@4.0.0
├── linter-php@1.4.0
├── linter-php7cc@1.0.1
├── linter-ui-default@1.6.8
├── minimap-linter@2.0.2
├── narrow@0.51.0
├── pane-browser@1.6.0
├── php-cs-fixer@4.1.1
├── php-integrator-annotations@1.2.0 (disabled)
├── php-integrator-autocomplete-plus@1.6.0 (disabled)
├── php-integrator-autocomplete-plus-legacy-php56@1.0.1
├── php-integrator-base@3.0.1 (disabled)
├── php-integrator-base-legacy-php56@1.0.1
├── php-integrator-call-tips@1.2.1 (disabled)
├── php-integrator-call-tips-legacy-php56@1.2.3
├── php-integrator-linter@1.3.0 (disabled)
├── php-integrator-linter-legacy-php56@1.3.1
├── php-integrator-navigation@1.2.1 (disabled)
├── php-integrator-navigation-legacy-php56@1.0.1
├── php-integrator-refactoring@1.4.1 (disabled)
├── php-integrator-refactoring-legacy-php56@1.0.1
├── php-integrator-symbol-viewer@0.6.4
├── php-integrator-tooltips@1.1.5 (disabled)
├── php-integrator-tooltips-legacy-php56@1.1.6
├── pigments@0.40.2
├── platformio-ide-terminal@2.6.0 (disabled)
├── project-manager@3.3.5
├── pure-syntax@0.3.0
├── qolor@0.4.2
├── Remote-FTP@1.1.3
├── solarized-seti-ui@0.8.6
├── split-diff@1.5.1
├── sync-settings@0.8.3 (disabled)
├── tail@0.1.0 (disabled)
├── tool-bar@1.1.0
└── tortoise-svn@0.5.1

I deinstalled the package and all is working. I waited at the start for a long time and then got a error message socket hang up.

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
