### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/snippets|c.json'

### ISSUE THREAD

**Issue by TheNowak** [atom-community/sync-settings#385]
Basically same as issue #384, but unselected "Sync Settings" option.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\TheNowak\.atom\snippets|c.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\TheNowak\.atom\snippets|c.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at /packages/sync-settings/lib/sync-settings.coffee:255:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
sync-settings 0.8.3 
```

**Comment by trackmystories** [comment]
Hey, this seems to be a file path issue, 

I have resolved this issue,

The issue I had been facing is with configuring my login page, (please see the screenshot to get an idea of the steps I took in-order to compile my app. 
<img width="841" alt="Screenshot 2019-04-27 at 11 03 36 PM" src="https://user-images.githubusercontent.com/43073387/56854098-67199a80-6942-11e9-8448-2658a3a663a1.png">


it seems that the file was not being located based on the error message and how it was defined in App.js, so what i did was i placed the file in a folder referencing the err message in correlation to the path defined in App.js (Please see screenshot) 
<img width="398" alt="Screenshot 2019-04-27 at 11 12 36 PM" src="https://user-images.githubusercontent.com/43073387/56854100-6bde4e80-6942-11e9-9976-30b99da5a147.png">

So my recommendation to resolve this issue would be to run the following checks:

1, Check if the file path is correctly referenced in App.js.
2, with reference to App.js place your file accordingly or create a folder and map out the file in App.js correctly.

You should get an idea through the screenshots provided.

**Comment by UziTech** [comment]
is this still an issue?

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
