### ISSUE TITLE
Need a way to tell if my configs are different from the backup

### ISSUE THREAD

**Issue by hugollm** [atom-community/sync-settings#388]
I was using the `check backup` command for this, but realized this only checks if there was a sync for the latest backup (probably by identifier). It doesn't tell me if my configurations are different than what's in it (a.k.a.: I need to `backup` or `restore`).

Is there a way to do this?

**Comment by dirk-thomas** [comment]
> Is there a way to do this?

No, not at the moment.

Duplicate of #18.
