### ISSUE TITLE
Delete package issue

### ISSUE THREAD

**Issue by msoedov** [atom-community/sync-settings#392]
The scenario:

- Disable one of the instaled apm packages (P) and sync between machines A and B
- Delete this package from A and run sync
- After sync that package will become enabled 

Expected:
- After sync package P should be deleted from both machines

Version 0.8.3, both machines running on  OSX

**Comment by dirk-thomas** [comment]
The function [removeObsoletePackages](https://github.com/atom-community/sync-settings/blob/f2904428aa24ce068d27cb5ac72b8c6be0b3e2c9/lib/sync-settings.coffee#L310) should exactly what you are describing. If you have enabled the corresponding [setting](https://github.com/atom-community/sync-settings/blob/f2904428aa24ce068d27cb5ac72b8c6be0b3e2c9/lib/config.coffee#L70) on machine B the package P should be removed when trigger the `restore` command on machine B.

**Comment by dirk-thomas** [comment]
Closing due to no response.
