### ISSUE TITLE
Add option to disable Sync Themes

### ISSUE THREAD

**Issue by chharvey** [atom-community/sync-settings#396]
Please add a checkbox for “**Sync Themes**” to the `sync-settings` package settings page. Or to be more granular, have two checkboxes: “**Sync UI Theme**” and “**Sync Syntax Theme**”.

This would be useful if you have two different computers between which you want to sync package settings, but you want to keep using different themes on the computers. Right now the only workaround is to “*Sync Settings: Restore*” and then readjust your themes.

**Comment by UziTech** [comment]
PRs are welcome
