### ISSUE TITLE
"Project directory atom://config is no longer on disk." Error after restoring settings. 

### ISSUE THREAD

**Issue by shaneknysh** [atom-community/sync-settings#397]
After restoring settings the next atom launch displays the error:

Project directory atom://config is no longer on disk.
![atom-error](https://user-images.githubusercontent.com/158361/34699564-46e9dd50-f49b-11e7-9952-a8c50f176838.png)

while also displaying the Welcome Guide panel and the Settings panel - as if this was the very first Atom launch.

**Comment by campriest** [comment]
is there a fix to this?

**Comment by dirk-thomas** [comment]
This sounds like being related to [this](https://github.com/atom/atom/pull/16628) fix in Atom itself.

Without further information there is sadly not much we can do here.

**Comment by shaneknysh** [comment]
Is there further information I can supply?

**Comment by dirk-thomas** [comment]
> Is there further information I can supply?

Version information, extra steps to reproduce, etc.

Try the latest beta release and check if the problem still exists with that.

**Comment by smoothdvd** [comment]
1.24.0 has still this warning

**Comment by mileserickson** [comment]
How can we help?

I just deleted my previous installation of atom (`brew cask remove atom`) and reinstalled the current version (`brew install atom`). It installed 1.24, and gave me the option to restart and install 1.25.

Once I launched 1.25, I went into Atom->Preferences to customize my environment, and _immediately_ saw the "Unable to open project directory: Project directory atom://config is no longer on disk." message in the upper right corner.

How can I troubleshoot this happening on a fresh installation? What is the default location referenced by `atom://config`? I'm on OS X Sierra 10.12.6.

**Comment by mileserickson** [comment]
Update: I made a guess that `atom://config` was somehow referencing `~/.atom`.

`rm -rf ~/.atom`, followed by restarting Atom, cleared the error. I presume that this resulted in a default configuration being restored to that directory.

**Comment by abraham** [comment]
I'm getting this with 1.25.0 when I open it via macOS spotlight. However if I open from the terminal with `atom .` I don't get the error.

**Comment by xenulv** [comment]
I got the error on 1.26.1, MacOS.

However when I invoked a project terminal with atom . (what @abraham suggested), the result is that I no longer see an error.

I should also note that I updated a package and I have an automatic sync from an upstream gist file. Not sure if any of you are using that or if it could affect anything.

**Comment by demetrios** [comment]
Problem persists in 1.29.0

**Comment by pasimako** [comment]
In my case, I first noticed the error message after I removed my previous snap installation in Ubuntu and then reinstalled from the official deb repo.

It seems that the problem occurs when there are no project folders in the tree view ( `[{"initialPaths":[]}]` in `~/.atom/storage/application.json`) and one attempts to open Preferences (where `[{"initialPaths":["atom://config"]}]`). However, as long as at least one file is open in the editor there are no errors. The first time that I opened a file I also got a message asking whether I want to restore a preexisting state.

After I completely removed `~/.config/Atom`, I no longer have this issue. Removing `~/.atom` did not make any difference.

Version: 1.34.0 x64 (Ubuntu)

**Comment by dnfupdatey** [comment]
file >>reopen project>>clear project history.  Easy to solve it

**Comment by UziTech** [comment]
is this still an issue?

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
