### ISSUE TITLE
Documentation: clarify how to set up in other instances

### ISSUE THREAD

**Issue by andreamoro-git** [atom-community/sync-settings#399]
One thing is not clear to me: once the packages is set up and running, how do I propagate settings in other instances? Should I copy the same gistId and personalAccessToken? Sorry maybe that's obvious.

**Comment by Nosenation** [comment]
You need to have installed this plugin in another atom with same gistID and personalAccessToken. Then on new machine you just do sync-settings:restore and it should install and setup all of yours plugins.

**Comment by binaryfunt** [comment]
Just to be clear, we have to use the **same** access token? If I go on GitHub, it won't let me view the token - I have to regenerate it. But this seems to mean I will have to change the token entered on my other device next time I use it.

So as I understand it, unless I write down the token, I will have to keep regenerating it each time I switch devices.

If this understanding is correct, the documentation should tell you to write down/store in some way the token.

**Comment by UziTech** [comment]
you have to use the same gist but not necessarily the same access token. You can see the access token in the settings if you want to use the same one.
