### ISSUE TITLE
I get a error message when I use environment variable in my shell config

### ISSUE THREAD

**Issue by in-in** [atom-community/sync-settings#419]
Package works properly, but when Atom starts for the first time, it shows the error: «_sync-settings: Mandatory settings missing: Gist ID, GitHub personal access token_»

![0018a](https://user-images.githubusercontent.com/8797432/37498778-3d0a0480-28d1-11e8-8d86-ae2768fa6190.png)

**Comment by dirk-thomas** [comment]
Which version version of this package are you using?

**Comment by in-in** [comment]
```bash
~|⇒ atom --version && apm list --installed --bare
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
sync-settings@0.8.5
```

**Comment by dirk-thomas** [comment]
I assume you have set the environment variables but haven't exported them.

If you do `GIST_ID=xxx` you can already output the variable with `echo $GIST_ID`. But you won't see the variable in this command: `env | grep GIST_ID`.

Therefore the variables are not visible to `atom`. You need to explicitly export them with: `export GIST_ID=xxx` or in your case you can do: `export GIST_ID=$GIST_ID`. Then `atom` will receive the environment variables and not show the warning anymore.

**Comment by in-in** [comment]
Of course, I exported the token and id as described in the README.md

My `.zshrc` looks like this
```bash
export GITHUB_TOKEN=6a10cc207b....7a67e871
export GIST_ID=b3025...88c41c
```

And the command
`env | grep GITHUB_TOKEN && env | grep GIST_ID`
shows me my token and id

**Comment by dirk-thomas** [comment]
Then I don't know why it doesn't work in your case. The code clearly uses the environment variables ([1](https://github.com/atom-community/sync-settings/blob/49bd959ce51b7d3f9f5738313c76e785f34a021d/lib/sync-settings.coffee#L470), [2](https://github.com/atom-community/sync-settings/blob/49bd959ce51b7d3f9f5738313c76e785f34a021d/lib/sync-settings.coffee#L53)). And it works for me just fine with exactly the setup you are describing. Maybe someone else has an idea...

**Comment by gbingersoll** [comment]
I see a similar problem. I have `GIST_ID` and `GITHUB_TOKEN` defined in `.zshrc`. I hacked in `console.log(process.env.GITHUB_TOKEN)` in `getPersonalAccessToken()` and I see `undefined` in the log when Atom launches.

If I put `console.log(process.env)` in the same place, though, in the developer tools I can see the correct value is set. But I'm not familiar enough with how the devtools work. That might be a delayed/async load.

Also, I noticed that if I launch Atom from the command line, it loads everything correctly. No error message. It's only when I launch from macOS finder or the spotlight search (`Cmd+Space`, type `Atom`, `return`) that the error messages appear for mandatory settings missing.

**Comment by dirk-thomas** [comment]
> It's only when I launch from macOS finder or the spotlight search that the error messages appear for mandatory settings missing.

In that case it might simply not ready your `.zshrc` file?

**Comment by gbingersoll** [comment]
It is getting the environment variables set through `.zshrc` eventually. If I launch Atom through Spotlight and look at `process.env` via the developer console, all the environment variables are there. It seems to be a question of when they get loaded relative to when sync_settings (or any other plugin) is looking at them.

**Comment by in-in** [comment]
I installed a new Ubuntu 18.04 on Virtualbox and tried Atom and _sync-settings_ with the default shell (bash). I place `GITHUB_TOKEN` and `GIST_ID` in `.bashrc`, and now it works correctly at startup no matter how you run it
