### ISSUE TITLE
Github Token disappeared twice this week 

### ISSUE THREAD

**Issue by kalimar** [atom-community/sync-settings#423]
Yesterday and today when I opened Atom the Github token and gist were gone. Let me know if there's any type of log or other settings I can submit to help debug.

**Comment by dirk-thomas** [comment]
Please provide steps to reproduce the problem as well the as the platform you are using and the versions of Atom and this plugin

**Comment by kalimar** [comment]
Thanks for the prompt response @dirk-thomas - I see there's an update so I'm going to update, add my token and gist again and try to watch for a pattern. If it doesn't happen again I'll close out the ticket on Monday. Otherwise I'll add a comment with all of the requested info.

Cheers 🍾

**Comment by grig0ry** [comment]
Today I ran into this. The problem was solved by updating Github Token.

**Comment by kalimar** [comment]
Updating the Github token the first day didn't work for me however upgrading `sync-settings` appears to have done the trick. I'm going to close the ticket.
Thanks

**Comment by grig0ry** [comment]
The problem is again relevant. After the run, the settings are not loaded. Error:
**sync-settings: Mandatory settings missing: Gist ID, GitHub personal access token**

**Comment by dirk-thomas** [comment]
> After the run, the settings are not loaded

@grig0ry Please provide exact steps how to reproduce the problem. Also information about your platform and version.

**Comment by manuelbieh** [comment]
Have the same issue every once in a while. Really annoying. Happens roughly every 4-6 weeks. The worst part of this issue is that all my editor settings are reset to default until I re-add the Gist ID and a new token and then re-sync my settings.

**Comment by SpawnTree** [comment]
Happened to me today. Really frustating. I run github commit-and-push from  a script on terminal and I have to generate a new token even 30~40 mins or so. Where is the problem? Why is it persisting so long???

**Comment by srwight** [comment]
I, too, am unable to create a persistent token. They do not persist beyond a few minutes.

Well, that may not be true. They seem to continue working when I use them with curl, but the very first time that _jenkins_ uses them with curl, they disappear. Attaching jenkinsfile.

[Dockerfile.txt](https://github.com/atom-community/sync-settings/files/4288960/Dockerfile.txt)

**Comment by UziTech** [comment]
@srwight What error are you getting? This package has nothing to do with jenkins.

**Comment by srwight** [comment]
A disappearing GitHub authentication token. But I figured it out.

**Comment by srinin01** [comment]
> A disappearing GitHub authentication token. But I figured it out.
@srwight My github tokens are also disappearing after I use with curl. What is the fix for this?

**Comment by srwight** [comment]
The fix is not to have your token in your repo. The issue is that GitHub
sanitizes your token for security.

It's a good play.

I don't remember what I did instead though. That was a minute ago!

**Comment by srinin01** [comment]
@srwight I think I am creating the token at the account level only, not from the repo. But it is still disappearing.

**Comment by srwight** [comment]
If GitHub finds an authentication token anywhere in your repository, it
will remove it. It may be sending you emails about it, too.
