### ISSUE TITLE
Atom continuously asks for the keys

### ISSUE THREAD

**Issue by manelmendez** [atom-community/sync-settings#428]
I don't know why but nearly every day atom deletes my key and Gist Id and I lose my config every time until I put my keys again and restore. I'm on MacOS.

Any solution? Thanks!

**Comment by webjoyable** [comment]
Same here.

v1.25.1 x64
Windows 10

**Comment by m1ga** [comment]
Same happend here today. Fedora Linux, Atom 1.25.1

**Comment by Alex-Linhares** [comment]
Same with me today, MacOs, Atom 1.25.1

**Comment by palsivertsen** [comment]
I reverted to v0.8.5. Seems to work fine

**Comment by palsivertsen** [comment]
Might be related to [this issue](https://github.com/atom/atom/issues/17060) resolved in the latest atom release (v1.26.1)

**Comment by m1ga** [comment]
Still happened in 1.26.1

**Comment by titovanton** [comment]
same issue: win10, installed win10 and atom 4 days ago from the scratch, before that - worked fine

**Comment by manelmendez** [comment]
Still happening, this is so annoying

**Comment by UziTech** [comment]
is this still an issue?

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
