### ISSUE TITLE
Is config.cson backed up?

### ISSUE THREAD

**Issue by saurabh-hirani** [atom-community/sync-settings#430]
Hi,

Thanks for creating sync-settngs. It is the easiest way to backup my atom config. I had a query - I was going through the backed up gist - and I saw that config.cson is not present. Is there a flag to enabled the same? It contains useful info like tablength depending on various languages, telemetry consent, etc.

**Comment by titovanton** [comment]
sounds like is related to https://github.com/atom-community/sync-settings/issues/428

**Comment by UziTech** [comment]
config settings are backed up to `settings.json` in the gist
