### ISSUE TITLE
how to roll back the last backup

### ISSUE THREAD

**Issue by bercly0b** [atom-community/sync-settings#436]
I installed atom and sync-setting on new computer and accidentally pressed 'backup' instead 'restore'. And now when I make restore it doesn't download my settings. Help me please) How to roll back the last backup? sorry for my stupidity..

**Comment by bercly0b** [comment]
I solve my issue like this: 
I just made backup in old computer and restore in new)

**Comment by UziTech** [comment]
you can see the revisions in the gist and restore them manually then back them up again
