### ISSUE TITLE
sync-settings: Error retrieving your settings. (Bad credentials)

### ISSUE THREAD

**Issue by mpaulose** [atom-community/sync-settings#450]

**Comment by Leon9021** [comment]
Can confirm that the issue is also present on Windows 10

**Comment by Phoenixalibur** [comment]
It's happening for me on Windows 10 right now too. It used to work for me with the exact same Gist. Now it doesn't for some reason. I didn't even have spaces or special characters.

**Comment by ChantalSchot** [comment]
I have the same issue, without changing anything in the Gist and no spaces/characters in the access token.

**Comment by UziTech** [comment]
This usually means the Personal Access Token has been deleted or removed from the settings.
