### ISSUE TITLE
Allow to scope settings by platform

### ISSUE THREAD

**Issue by ryinaya** [atom-community/sync-settings#462]
Hello.
I develop on different platforms. Some packages need different settings (ex. paths) by platforms.
I heard setting-sync on VSCode has the features that can set parameters for each platform.
So, it could be great if we had a per platform settings set, as same as VSCode.
Or, is there any way to do that on sync-settings in atom already?

(I posted an issue for the first time in my life, and my English is not good. If I have something rude, I'm sorry.)

**Comment by UziTech** [comment]
Do you want different settings on different platforms? Could you just set different gists for each platform?

**Comment by hovancik** [comment]
It would be nice indeed. From what I understand, my Atom linters only work on macOS because of that.

**Comment by UziTech** [comment]
How would sync-settings know which settings should be synced between platforms and which should not?

**Comment by hovancik** [comment]
hey @UziTech sorry, I deleted my post meanwhile, the problem was elsewhere for me.  If what @ryinaya says is true, then I guess we could take a look there.

**Comment by UziTech** [comment]
closing as duplicate of #159
