### ISSUE TITLE
Received a... few "...using the `access_token` query parameter is deprecated." emails today

### ISSUE THREAD

**Issue by jpartain89** [atom-community/sync-settings#463]
I had received a few emails from Github today, all saying the same thing, pointing to my syncing `gist` file...

> Hi @jpartain89, 
> 
> On February 4th, 2020 at 03:26 (UTC) your personal access token (Atom Syncing) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API: 
> 
> api.github.com/gists/###hidden_because_i_said_so###
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. 
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf. 
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all. 
> 
> Visit developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information. 
> 
> Thanks, 
> The GitHub Team 

Any plan/word on updating this?

Thanks.

**Comment by enginpost** [comment]
Is there an update available that will resolve this? I just got this error message today and Atom doesn't say there is an update for Sync Settings available for download.

**Comment by jfletcher-nuxeo** [comment]
There's a pull request (#464) that supposedly resolves this but there's apparently no one maintaining the package to accept it.

**Comment by maurice-schleussinger** [comment]
@BinaryMuse @50Wliu @basarat
Could we get a statement or decision about the future of this package/repo?

**Comment by pauljherring** [comment]
> There's a pull request (#464) that supposedly resolves this

And a few other things judging by the line count...

**Comment by UziTech** [comment]
The release that fixes this should be available 🎉

**Comment by pauljherring** [comment]
> The release that fixes this should be available 

Doesn't appear to be; at the time of writing https://atom.io/releases shows the most recent release as v1.43.0 (2020-01-14)

**Comment by gilbertohasnofb** [comment]
@pauljherring Those are the releases of Atom itself, not of this package. You can see that version `2.0.0` has been released [here](https://github.com/atom-community/sync-settings/releases). You can update it directly in Atom by going to settings and looking for available updates for your installed packages.

@UziTech I just tested it and the issue has been resolved on my side. Thank you so much for the fix and for stepping up to become a maintainer of this package, that's really appreciated.

**Comment by pauljherring** [comment]
> Those are the releases of Atom itself, not of this package.

Doh! I'm sorry.

**Comment by al-yakubovich** [comment]
I am still receiving emails from GitHub with this notice.

**Comment by UziTech** [comment]
@al-yakubovich have you installed the latest version?
