### ISSUE TITLE
Change to Authorisation HTTP Header, from access_token

### ISSUE THREAD

**Issue by QuaCKeReD** [atom-community/sync-settings#465]
As per emails from GitHub, the access_token integration is now depracted, and Autorisation HTTP Header should be used instead. Is this on roadmap for change and, if not, what can we do to continue using sync-settings?

Email;
Hi xxx,

On February 6th, 2020 at 16:43 (UTC) your personal access token (Atom.io sync-settings) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/gists/abc123

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

**Comment by UziTech** [comment]
This should be fixed in v2.0.0 just released a few minutes ago

#464

**Comment by QuaCKeReD** [comment]
Timing 😀

Thanks
