### ISSUE TITLE
`access_token` query parameter is deprecated and will be removed July 1st, 2020.

### ISSUE THREAD

**Issue by Micronetic** [atom-community/sync-settings#476]
On February 9th, 2020 at 11:01 (UTC) your personal access token (atom editor) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/gists/*********

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by maurice-schleussinger** [comment]
See https://github.com/atom-community/sync-settings/issues/463

**Comment by UziTech** [comment]
This is fixed in the newest version
