### ISSUE TITLE
You have selected to use an other backup location but none are installed.

### ISSUE THREAD

**Issue by p0bailey** [atom-community/sync-settings#499]
**Describe the bug**
Having installed https://atom.io/packages/sync-settings-git-location and works perfectly. However everytime I start atom I get this message. 

Sync-Settings: No Location Service

You have selected to use an other backup location but none are installed.

**Comment by UziTech** [comment]
Does it happen on ***every*** reload? The initial check should be waiting until all other packages are activated.

**Comment by UziTech** [comment]
What version of Atom and Sync-Settings are you using?

**Comment by p0bailey** [comment]
Hi Tony,
Thanks for your amazing plugin. After rebooting my mac the problem has disappeared.

For me you can close the issue.

Kind regards,

Phillip

**Comment by UziTech** [comment]
Thanks for reporting and helping debug :+1:
