### ISSUE TITLE
Popup always, but only timestamp is different

### ISSUE THREAD

**Issue by miskovics** [atom-community/sync-settings#502]
**Describe the bug**

Whenever I start Atom, I get

```
Sync-Settings: Your settings have changed since your last backup.

Last Backup: 3/21/2020, 9:43:20 AM
```

When I click <kbd>View diff</kbd>, then the only difference found is the backup timestamp.

![image](https://user-images.githubusercontent.com/26648359/77241887-19acb880-6bf9-11ea-9ee1-080f4185acb6.png)

**To Reproduce**
(Re)start Atom.

**Expected behavior**

Pop-up comes only if there is a real change.

**Screenshots**

**Versions**
 - OS: Ubuntu 19.10
 - Atom: 
1.45.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node: v10.11.0

 - APM: 
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.20.1

**Additional context**

**Comment by UziTech** [comment]
It looks like the package `autoupdate-packages` has changed a setting. This correctly notifies you that your settings have changed.

You should be able to add that key to the blacklisted keys to prevent sync-settings from backing up that key.

![image](https://user-images.githubusercontent.com/97994/77243023-05ee5b80-6bd3-11ea-8b8a-db0828e3b0e5.png)

**Comment by miskovics** [comment]
Yes, that did it! Thank you!
