### ISSUE TITLE
"Your backup has changed since your last restore" every time I launch Atom

### ISSUE THREAD

**Issue by bskendig** [atom-community/sync-settings#503]
I have Atom 1.45.0 installed on a few different computers (macOS and Windows) and I use sync-settings 4.3.2 to sync the settings between them. (I'm only running Atom on one computer at a time, and I quit it when I'm finished with it.) I'm storing my settings in a private gist.

Every time I launch Atom, I get a message:

> Sync-Settings: Your backup has changed since your last restore.

It shows me my last backup and last restore times, and yes, the backup is more recent because another computer wrote it. If I click Restore, then the next time I launch it on this computer, I get:

> Sync-Settings: Your settings have changed since your last backup.

If I click Backup, then the problem goes away for this computer ... but then the same thing will happen on another computer as soon as I launch Atom there.

I'm using sync-settings to synchronize my Atom settings between computers; it seems odd that it would complain when another computer updates the settings.

I saw another issue here with a few recommendations, so I checked: I only have an "init.coffee" file (not "init.js"), and I added a file named "a.txt" to my gist so that the gist would not be named init.coffee.

**Comment by bskendig** [comment]
I clicked "View Diff", and it shows me:
`sync-settings@4.2.0` in red, and
`sync-settings@4.3.2` in green.
I didn't realize this computer hadn't updated sync-settings. So I updated it and re-launched Atom, and now there was no error.

But, on a hunch, I went in to the Atom settings and changed one item (I turned off "Audio Beep"). I quit and relaunched Atom, and sync-settings is telling me again that the backup has changed. I click "View Diff" and it shows me
`core.audioBeep: false` in red.

Weird that it seems to be complaining when its own settings are different from its own backup.

**Comment by UziTech** [comment]
It alerts you any time the backup is different from your current settings. Why is that weird? Do you not want it to alert you when the local settings are different from the backup?

**Comment by bskendig** [comment]
Oh - I thought sync-settings was going to sync my settings automatically; loading them each time I launch Atom, and backing them up each time I changed them (or, alternately, when I quit). I didn't realize that it expected me to trigger the loading and saving of them each time.

(This isn't a complaint about sync-settings; just a misunderstanding on my part of what it meant by 'synchronize'. It's more of an online settings backup.)

Is there any way to configure Atom to give sync-settings that automatic behavior? Or to have a single sync command which merges the local settings with the backup and then updates the backup?

**Comment by bskendig** [comment]
And when the backup is different from the local settings, displaying this as an error message with a red background might not be the best way to handle it. Perhaps a message like "Your backup has changed since your last restore; load it? [yes/no]" or "Your settings have changed since your last backup; back them up? [yes/no]"

**Comment by UziTech** [comment]
> Is there any way to configure Atom to give sync-settings that automatic behavior?

There is an issue for backing up automatically (#317). If you want to create a PR I would be happy to review it. 😁

> Or to have a single sync command which merges the local settings with the backup and then updates the backup?

How would sync-settings know which settings you want to keep from the local settings and which to keep from the backup? There is a backup command to overwrite your backup with local settings and a restore command to overwrite your local settings with your backup.

> Perhaps a message like "Your backup has changed since your last restore; load it? [yes/ignore]" or "Your settings have changed since your last backup; back them up? [yes/ignore]"

The notification should have a yellow background. And the message does change depending on if the backup has changed or local settings have changed.

Backup changed: "Your backup has changed since your last restore."
Local changed: "Your settings have changed since your last backup."

**Comment by bskendig** [comment]
Merging files needn't be difficult; if the backup has settings that don't exist locally then use them, if there are other differences between local and backup then resolve them in favor of which every file is more recent. (Though I realize that's a feature request.)

The notification is red:

<img width="461" alt="Screen Shot 2020-03-29 at 9 13 22 PM" src="https://user-images.githubusercontent.com/1202806/77867001-639e2b80-7203-11ea-84b0-ff7b7cfba434.png">

**Comment by UziTech** [comment]
Atom doesn't save when settings are changed so how does sync-settings know which settings are more recent if local settings have changed and backup is changed?

![image](https://user-images.githubusercontent.com/97994/77868822-1a99a780-7202-11ea-9654-6be105ffe47e.png)

It is yellow with one dark theme. It is a warning not an error.

**Comment by bskendig** [comment]
It's red for me, as in the screenshot I posted. I'll check to see if I have any theme installed, but I don't believe that I do.

"How does sync-settings know which settings are more recent if local settings have changed and backup is changed" - well, right now it displays an error on launch which tells me the timestamps on the local settings and the backup settings. Merging the two settings files, with preference for whichever settings file has been modified most recently, would probably be enough in the majority of situations.

**Comment by UziTech** [comment]
It knows when the backup changed and that the local settings changed but how can it know which settings changed when? should it always do a `restore` if the backup changes and a `backup` if the local settings changed? what happens when both change?

**Comment by UziTech** [comment]
Like I said if you want to do a PR I would be happy to review it.

**Comment by bskendig** [comment]
"Should it always do a restore if the backup changes and a backup if the local settings changed?" Sure, why not? Honestly - simplistic merging like that isn't going to work if, say, you have several team members all working on different parts of a source code file; you don't want the most recent copy of the file to overwrite everybody else's changes. But with Atom, (a) you're probably only synchronizing different Atom installations that one person (you yourself) uses; (b) you're probably only using one Atom installation at a time; and (c) you're probably not changing your settings very often.

When Atom launches and sync-settings checks the local and backup timestamps, and they're different - instead of displaying an error, just quietly merge the settings with all conflicts being won by the newer copy of the file, and write it to backup. And every time the local settings change, write it to backup.

I haven't written JavaScript for a few years, but I'll have a look if I have a chance.

**Comment by UziTech** [comment]
>  (a) you're probably only synchronizing different Atom installations that one person (you yourself) uses; (b) you're probably only using one Atom installation at a time; and (c) you're probably not changing your settings very often.

Those "probably"'s are the problem. If they do happen then settings get overwritten that shouldn't have.

**Comment by bskendig** [comment]
Okay, that's a good point. :)

But that's why I suggested above: instead of giving the user all the options to Backup / Restore / View Backup / View Diff / Stop Automatic Check, you could  just say something like "your [local/backup] settings are older. Merge them with your [backup/local] settings and back up? [yes] [ignore]"

The point being that the only two things a user is likely to do when there's a conflict are to either merge the settings, or ignore the conflict. Right now, entirely overwriting the backup with local or the local with backup are less ideal solutions.

Just my two cents.

**Comment by UziTech** [comment]
Again "likely" is the problem. When writing software you have to accommodate **all** users not just the most likely. If there was a reason we could only have two buttons I would agree with you but I don't see any benefit in removing the options that users currently have.

**Comment by xnervwang** [comment]
This message started to show recently while I have used this plugin for years... Every time I clicked "Restore" then restarted Atom then the message showed again. Didn't investigate the details but I just select "Stop Automatic Check".

**Comment by UziTech** [comment]
@xnervwang If you click View Diff it will show you what is changed between your local files and backup.
