### ISSUE TITLE
sync-settings: Error restoring settings

### ISSUE THREAD

**Issue by jon-childs** [atom-community/sync-settings#504]
When trying to do a restore, I get the the error "packages.filter is not a function". 

![Screen Shot 2020-04-13 at 8 08 19 PM](https://user-images.githubusercontent.com/2837721/79178467-9c70ff80-7dc2-11ea-91ae-b7b88f13e448.png)

**Comment by UziTech** [comment]
What version of Atom are you using?

**Comment by UziTech** [comment]
Also what version of sync-settings are you using?

**Comment by UziTech** [comment]
It looks like that error message is from before version 4. Try updating sync-settings and try it again. If it still gives you an error message feel free to reopen this issue.

**Comment by jon-childs** [comment]
Updating the sync-settings did the trick. Sorry, I should have realized! Thanks!
