### ISSUE TITLE
Bug: Erroneous changed notifications

### ISSUE THREAD

**Issue by sbrl** [atom-community/sync-settings#505]
**Describe the bug**

Every time I start Atom recently, sync settings claims that my settings have changed since my last backup, which is not true. See below.

**To Reproduce**
1. Setup sync settings
2. Close Atom
3. Open Atom
4. See erroneous changed notification

**Expected behavior**

The change notification should only appear when I've changed my settings.

**Screenshots**

![Sync Settings: Diff — Atom_040](https://user-images.githubusercontent.com/9929737/79568027-12b87f00-80ad-11ea-851e-861dd94fd0bd.png)

**Versions**
 - OS: Ubuntu 19.10 (`Linux LAPTOP_NAME 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)
 - Atom: `Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0`

 - APM: `apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.20.1`

**Additional context**

**Comment by UziTech** [comment]
It looks like you have a file called `init.coffee` that is in your backup but not in your local `.atom` folder.

If you click restore the file will be created and the notification should go away. Alternatively you can remove the file from the backup.

**Comment by sbrl** [comment]
Hey, thanks for the reply @UziTech! I've tried pressing restore on it more than once, but unfortunately it doesn't appear to have any effect :-(

Excluding it from the backup would workaround the issue, but then if I later start editing it I might forget that I'd excluded it.....

**Comment by UziTech** [comment]
> but then if I later start editing it I might forget that I'd excluded it.....

Start editing what?

**Comment by sbrl** [comment]
Sorry, I might not have been clear there. If I exclude `init.coffee` from `sync-settings`, that would work around the issue. However, if I later want to customise `init.coffee` and sync it, I'm likely to forget that I'd explicitly ignored it and get confused.

**Comment by UziTech** [comment]
by `"remove the file from the backup"` I meant literally go to your gist and delete the file from the backup not exclude it from your backup. According to the diff you don't have an `init.coffee` file locally anyway.

**Comment by sbrl** [comment]
Ah I see haha! I must have mis-interpreted that :P

That's so strange! Deleting it from the remote fixed it.
