### ISSUE TITLE
Unable to run commands after installation

### ISSUE THREAD

**Issue by LouisOuellet** [atom-community/sync-settings#509]
After install sync-settings and configuring it, I am unable to run any of it's command. Rendering it useless.

1. Install Sync-Settings
2. Go to Settings
3. Configure Access Token and GIST ID
4. CTRL+P and type sync-settings:restore
5. "No Matches found"

**Expected behavior**
Command is found and runs

**Versions**
 - OS: Elementary OS 5.1.3 Hera (Ubuntu 18.04 LTS)
 - Atom: 1.26.1
- Electron: 1.7.11
- Chrome: 58.0.3029.110
- Node: 7.9.0
- APM: 1.19.0
- npm: 3.10.10
- node 6.9.5 x64
- python 2.7.17
- git: 2.17.1

**Additional context**
I was trying to sync settings from my workstation to my laptop. Sync-Settings worked fine on my workstation. And I was able to run the backup command. Now I wanted to run the restore command on my laptop to sync the settings. Because I had many differences such as tab space and stuff. Causing the code I am working on to be differently formatted on both machine. Making formatting a problem.

**Comment by LouisOuellet** [comment]
Fixed the issue by adding the repository in my package list and updated Atom

**Comment by SalahNasr95** [comment]
> Fixed the issue by adding the repository in my package list and updated Atom

I have the same problem, can you explain what you did further?
