### ISSUE TITLE
sync-settings almost always reports github@0.34.2 has changed at Atom startup 

### ISSUE THREAD

**Issue by ipkpjersi** [atom-community/sync-settings#570]
**Describe the bug**
After trying Atom again for the first time in a couple years, almost every launch of Atom sync-settings now has reported that I do not have the latest changes backed up. I think this issue is caused by the github package changing from a community package to an official package. However, I do not have the github community package installed anymore, and running `apm uninstall github` on both of my PCs where I sync Atom settings do not have the github community package installed anymore.

**To Reproduce**
1. Launch Atom
2. See the changes popup

**Expected behavior**
I expect the popup to not show up almost every single launch when nothing has actually changed.

**Screenshots**
Here is the diff (indicating the cause of the issue): 
![](https://i.imgur.com/7CnuFBO.png)

**Versions**
 - OS: Ubuntu 18.04
 - Atom: 1.51.0

 - APM: 
```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.51.0
python 2.7.17
git 2.17.1
```

**Comment by UziTech** [comment]
Have you tried clicking Backup? It should overwrite your current backup with your current settings and remove `github@0.34.2` from the backup.

**Comment by ipkpjersi** [comment]
Oh, I forgot to mention, yes I have clicked backup every single time, and it still prompts me almost every other launch - hence why reporting it as a bug.

**Comment by UziTech** [comment]
Can you provide your sync-settings configuration?

**Comment by ipkpjersi** [comment]
Sure I can provide it, with sensitive information removed of course:

```cson
"sync-settings":
    gistId: "removed"
    hiddenSettings:
      _lastBackupTime: "2020-10-02T15:26:45Z"
    personalAccessToken: "removed"
    quietUpdateCheck: true
    removeObsoletePackages: true
```
I have also attached my entire sync-settings backup zip in case that helps.
[1283cc9f2179bbed0c6817807cd6253d-a14e4fec30f86f42a16b06ec24befe92e2aa9335.zip](https://github.com/atom-community/sync-settings/files/5319171/1283cc9f2179bbed0c6817807cd6253d-a14e4fec30f86f42a16b06ec24befe92e2aa9335.zip)

**Comment by UziTech** [comment]
You can try checking the Only Sync Community Packages setting

![image](https://user-images.githubusercontent.com/97994/94946153-52c7be80-04a1-11eb-9758-dc519450c4b3.png)

Then click backup and see if it fixes it.

**Comment by ipkpjersi** [comment]
That seems to have done the trick so far. However, with that setting selected, does that mean the enabled status of the bundled packages will not be synced?

For example, I have certain bundled packages disabled like the github package because I prefer using github outside of Atom. Would "Only Sync Community Packages" still preserve the disabled status of the github package (and other bundled packages) when restoring a backup via sync-settings?

**Comment by UziTech** [comment]
Yes it will preserve the disabled packages since that is just a setting in config.cson

**Comment by UziTech** [comment]
This seems fixed so I am going to close it.
