### ISSUE TITLE
Sync Settings Backup does not appear in the Command Palette

### ISSUE THREAD

**Issue by carloscuesta** [atom-community/sync-settings#622]
**Describe the bug**

Hello! I've been using this package for years and I love it! But since few weeks ago when I want to manually backup my settings but the Sync Settings Backup option does not appear on the command palette.

**To Reproduce**

1. Open the command palette
2. Write Sync settings
3. No command is available.

**Expected behavior**

I expect to see the command to back up my settings.

**Screenshots**

![Screenshot 2021-01-06 at 11 17 26](https://user-images.githubusercontent.com/7629661/103757270-d1884680-5010-11eb-82e2-bdc6fe45d9b4.png)

![Screenshot 2021-01-06 at 11 18 41](https://user-images.githubusercontent.com/7629661/103757412-085e5c80-5011-11eb-8efe-c8e05677c500.png)

**Versions**
 - OS: macOS Big Sur
 - Atom: 1.35.1
 - APM: 2.1.3

Thanks!

**Comment by UziTech** [comment]
That is strange, the commands haven't changed recently and I can still see them in my command palette.

The only thing I can think is Atom v1.35.1 is pretty old, maybe try updating Atom?

**Comment by carloscuesta** [comment]
Hey @UziTech thanks for the quick response! My bad I didn't know I was using a version that old! Somewhat the "Check for updates" box got unchecked 😓 🤦🏼 

After updating to the last version everything is working properly ❤️ 

Sorry for the inconvenience and thanks for the quick response I really appreciate it 😊
