### ISSUE TITLE
Installing “sync-settings@5.2.9” failed with npm error

### ISSUE THREAD

**Issue by nhchan** [atom-community/sync-settings#675]
I was trying to update `sync-settings` from 5.2.7 to 5.2.9 (via the GUI), and got the following error output:
```
npm ERR! Unexpected end of JSON input while parsing near '...Version: OpenPGP.js v'
```
I have attached the corresponding [2021-04-20T14_47_44_064Z-debug.log](https://github.com/atom-community/sync-settings/files/6344505/2021-04-20T14_47_44_064Z-debug.log) file. 

I tried uninstalling the package altogether and reinstall, but the (re-)installation failed with the same error.

I am running Atom 1.56.0 (Electron 9.4.4, Chrome 83.0.4103.122, Node v12.14.1) on macOS 11.2.3.

Please advise. Thank you!

**Comment by UziTech** [comment]
sync-settings doesn't use `OpenPGP.js` in any way so this seems like an issue with apm or Atom. You could try uninstalling and reinstalling `sync-settings`.
