### ISSUE TITLE
Error "Unexpected end of JSON input" when trying to backup

### ISSUE THREAD

**Issue by followthemadhat** [atom-community/sync-settings#707]
I get this error when trying to backup:

```
invalid json response body at [gist]
 reason: Unexpected end of JSON input
```

I just created a new token and gist but it didn't help. Any ideas on how this can be fixed?

I use Atom 1.57.0 and sync-settings 5.2.12.

**Comment by UziTech** [comment]
Can you provide the whole stack trace?

**Comment by followthemadhat** [comment]
> Can you provide the whole stack trace?

![Screen Shot 2021-06-29 at 9 30 27 PM](https://user-images.githubusercontent.com/16475806/123834850-4df54580-d921-11eb-8dae-1971a21906cf.png)

**Comment by aklaver** [comment]
I see the same error and traceback with Atom 1.57.0 and sync-settings 5.2.12.

**Comment by UziTech** [comment]
Is this something that just started happening in v5.2.12?

**Comment by followthemadhat** [comment]
It was fixed for me without any additional actions, the error is now gone... maybe it was just a glitch in the system
