### ISSUE TITLE
Automatic updating to remote gist would be lovely.

### ISSUE THREAD

**Issue by Leopere** [atom-community/sync-settings#76]
I would adore the ability to be added to have this automagically be done.  I have two workstations my portable one (laptop) and my home one (desktop) I'd love to be able to have both workspaces have these things synced.

**Comment by jerone** [comment]
Possible dup: https://github.com/Hackafe/atom-sync-settings/issues/27

**Comment by chamunks** [comment]
I like the idea of #27 but I would almost prefer just a periodical diff check and on close check/save.

**Comment by UziTech** [comment]
closing as dup of #27
