### ISSUE TITLE
Sync package removals

### ISSUE THREAD

**Issue by weichert** [atom-community/sync-settings#91]
Maybe it's just me but it seems that package removals are not synced.
This should at least be an option. Others might like the current behavior.

**Comment by groupsky** [comment]
Currently packages are only installed if missing, no check is implemented to remove extra packages.

**Comment by dsifford** [comment]
:+1: This feature would be super helpful.

To expand on this with a potential temporary solution -- what about returning a popup alert of packages that don't match the backup on init?

That way users can go in and remove uninstalled packages before running a backup.

Thanks for the hard work!

**Comment by masavini** [comment]
+1 for dsifford proposal!

**Comment by mautematico** [comment]
I woul'd love to have this, also. :)
I'll see if there is something I can do on this and open a PR.

Thanks for the hard work!

**Comment by sksea** [comment]
:+1: for this feature and really appreciate your package!

**Comment by GuillaumeAmat** [comment]
Is there any news on that issue?
