### ISSUE TITLE
Feature Request: Keep local disabled status of package

### ISSUE THREAD

**Issue by nick-woodward** [atom-community/sync-settings#92]
## Request

It'd be convenient if there was a setting to retain the local packages disabled status.
## Use Case

My work uses jshint whereas I use eslint at home. 
Obviously I don't want [linter-eslint](https://github.com/AtomLinter/linter-eslint) and [linter-jshint](https://github.com/AtomLinter/linter-jshint) to be enabled simultaneously.

**Comment by mehcode** [comment]
Just noticed this. This sounds interesting but I'd recommend to extend it to a more general "profiles" feature (distinct, possibly named, sets of settings that can be switched between). This would allow @TheMetabyte to easily work from home one day if so desired.

**Comment by dirk-thomas** [comment]
This has already been implemented a while ago, see #329.
