### ISSUE TITLE
Support synchronizing binary files

### ISSUE THREAD

**Issue by mauricioszabo** [atom-community/sync-settings#93]
On my settings, I have the setting "Extra Files" set to "bgs/command.jpg". The file exists, but when I try to backup my settings it fails with the following message:

> error backing up data: {"message":"Validation Failed","errors":    [{"resource":"Gist","code":"invalid","field":"files"}],"documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"} exports.HttpError {message: "{"message":"Validation Failed","errors":[{"resourc…ps://developer.github.com/v3/gists/#edit-a-gist"}", code: 422, toString: function, toJSON: function}

Atom 1.0.0
Sync Settings 0.5.0

**Comment by jerone** [comment]
_TLTR: it's not possible to sync images._

Today I had the time to have a look at this issue. Right now it's **not** possible to sync images or any other binary file for that matter with sync-settings. Only UTF8 documents are synced atm.

Normally it's not possible to add images to GitHub Gists. However, an hidden feature of GitHub Gists makes it possible to upload images through source control (git). Doing this through [API](https://developer.github.com/v3/gists/#create-a-gist) seems not possible. I have sent GitHub a mail confirming this. Also with [third-party modules](http://mikedeboer.github.io/node-github/#gists.prototype.create) it's seems impossible.

One solution I can think of is to base64 encode the image before uploading it to a gist. This will show up as standard text on the gist. On restore, the base64 item can be converted back to an image. Problem with this is probably file size, but I'm not sure what are the limits.

    data = fs.readFileSync path.join atom.getConfigDirPath(), 'atom.png'
    console.log data
    data = new Buffer(data).toString('base64')
    console.log data
    files =
      'atom.png':
        content: data
        type: 'image/png'
    console.log files

**Comment by jerone** [comment]
This the answer I got from GitHub:

> There's no special API endpoint for uploading images to Gists, Jeroen. I agree that would be helpful, though -- I'll pass the suggestion to the team to consider, but can't make any promises.
Cheers,

With that in mind, uploading images will probably won't happen for some time. The best alternative solution is encoding to base64.

**Comment by deeperx** [comment]
I'm trying to sync my ~/coffeelint.json file (_which is text as you guess_) and I'm getting the same error...

**Comment by abbiekressner** [comment]
If I list "~/.gitconfig" or "~/.gitconfig," in the Extra Files field, I am unable to make a backup due to this Validation Failed error. When I clear the Extra Files field, I can successfully make a backup.

**Comment by richarddewit** [comment]
I got no error while backing up, but when I look at my gist, the image is displayed like this:

```
����JFIFHH��<CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 100
��C��C��q�"��	
��P!1AQaq�������"�2�#BR$3br�%4CS�5s���DTc�����6����B!1AQaq��������"2�3BR#r�4��Cb���S$����?�l�v#o��>k����

... etc
```

and when I view this image by downloading/restoring I get a notification that the image is corrupt.

**Comment by UziTech** [comment]
looks like this will require #267 or #351

**Comment by UziTech** [comment]
Sync-Settings now allows other packages to provide a location for the backup. You can install [sync-settings-folder-location](https://atom.io/packages/sync-settings-folder-location) and follow the install instructions to use a folder for the backup location.

I think in order to get this to work we will need to be able to detect non-text files and use a buffer or base64 string instead of a utf8 string to save the content.
